require-module kakounicode_ifte

declare-option -docstring 'Enable TeX kakounicode aliases (minus the Greek letters; see greek.kak).' \
    str kakounicode_enable_TeX false

hook global ModuleLoaded kakounicode_db %{
    if %opt{kakounicode_enable_TeX} %{ require-module kakounicode_TeX }
}

provide-module kakounicode_TeX %፠

echo -debug "loading kakounicode_TeX"

add-unicode '¡' '!`' 'Inverted exclamation mark'
add-unicode '–' '--' 'En dash'
add-unicode '¿' '?`' 'Inverted question mark'
add-unicode '̈' '"' 'Combining diaeresis'
add-unicode '́' '''' 'Combining acute accent'
add-unicode '̇' '.' 'Combining dot above'
add-unicode '̄' '=' 'Combining macron'
add-unicode '̋' 'H' 'Combining double acute accent'
add-unicode 'Ł' 'L' 'Latin capital letter l with stroke'
add-unicode 'Ø' 'O' 'Latin capital letter o with stroke'
add-unicode '¶' 'P' 'Pilcrow sign'
add-unicode '§' 'S' 'Section sign'
add-unicode '̂' '^' 'Combining circumflex accent'
add-unicode '̀' '`' 'Combining grave accent'
add-unicode '̱' 'b' 'Combining macron below'
add-unicode '̧' 'c' 'Combining cedilla'
add-unicode '̣' 'd' 'Combining dot below'
add-unicode 'ı' 'i' 'Latin small letter dotless i'
add-unicode '̨' 'k' 'Combining ogonek'
add-unicode 'ł' 'l' 'Latin small letter l with stroke'
add-unicode 'ø' 'o' 'Latin small letter o with stroke'
add-unicode '̆' 'u' 'Combining breve'
add-unicode '̌' 'v' 'Combining caron'
add-unicode '̃' '~' 'Combining tilde'
add-unicode '⁽' '^(' 'Superscript left parenthesis'
add-unicode '⁾' '^)' 'Superscript right parenthesis'
add-unicode '⁺' '^+' 'Superscript plus sign'
add-unicode '⁻' '^-' 'Superscript minus'
add-unicode '⁰' '^0' 'Superscript zero'
add-unicode '¹' '^1' 'Superscript one'
add-unicode '²' '^2' 'Superscript two'
add-unicode '³' '^3' 'Superscript three'
add-unicode '⁴' '^4' 'Superscript four'
add-unicode '⁵' '^5' 'Superscript five'
add-unicode '⁶' '^6' 'Superscript six'
add-unicode '⁷' '^7' 'Superscript seven'
add-unicode '⁸' '^8' 'Superscript eight'
add-unicode '⁹' '^9' 'Superscript nine'
add-unicode '⁼' '^=' 'Superscript equals sign'
add-unicode 'ᴬ' '^A' 'Modifier letter capital a'
add-unicode 'ᴮ' '^B' 'Modifier letter capital b'
add-unicode 'ꟲ' '^C' 'Modifier letter capital c'
add-unicode 'ᴰ' '^D' 'Modifier letter capital d'
add-unicode 'ᴱ' '^E' 'Modifier letter capital e'
add-unicode 'ꟳ' '^F' 'Modifier letter capital f'
add-unicode 'ᴳ' '^G' 'Modifier letter capital g'
add-unicode 'ᴴ' '^H' 'Modifier letter capital h'
add-unicode 'ᴵ' '^I' 'Modifier letter capital i'
add-unicode 'ᴶ' '^J' 'Modifier letter capital j'
add-unicode 'ᴷ' '^K' 'Modifier letter capital k'
add-unicode 'ᴸ' '^L' 'Modifier letter capital l'
add-unicode 'ᴹ' '^M' 'Modifier letter capital m'
add-unicode 'ᴺ' '^N' 'Modifier letter capital n'
add-unicode 'ᴼ' '^O' 'Modifier letter capital o'
add-unicode 'ᴾ' '^P' 'Modifier letter capital p'
add-unicode 'ꟴ' '^Q' 'Modifier letter capital q'
add-unicode 'ᴿ' '^R' 'Modifier letter capital r'
add-unicode 'ᵀ' '^T' 'Modifier letter capital t'
add-unicode 'ᵁ' '^U' 'Modifier letter capital u'
add-unicode 'ⱽ' '^V' 'Modifier letter capital v'
add-unicode 'ᵂ' '^W' 'Modifier letter capital w'
add-unicode 'ᵃ' '^a' 'Modifier letter small a'
add-unicode 'ᵇ' '^b' 'Modifier letter small b'
add-unicode 'ᶜ' '^c' 'Modifier letter small c'
add-unicode 'ᵈ' '^d' 'Modifier letter small d'
add-unicode 'ᵉ' '^e' 'Modifier letter small e'
add-unicode 'ᶠ' '^f' 'Modifier letter small f'
add-unicode 'ᵍ' '^g' 'Modifier letter small g'
add-unicode 'ʰ' '^h' 'Modifier letter small h'
add-unicode 'ⁱ' '^i' 'Superscript latin small letter i'
add-unicode 'ʲ' '^j' 'Modifier letter small j'
add-unicode 'ᵏ' '^k' 'Modifier letter small k'
add-unicode 'ˡ' '^l' 'Modifier letter small l'
add-unicode 'ᵐ' '^m' 'Modifier letter small m'
add-unicode 'ⁿ' '^n' 'Superscript latin small letter n'
add-unicode 'ᵒ' '^o' 'Modifier letter small o'
add-unicode 'ᵖ' '^p' 'Modifier letter small p'
add-unicode '𐞥' '^q' ''
add-unicode 'ʳ' '^r' 'Modifier letter small r'
add-unicode 'ˢ' '^s' 'Modifier letter small s'
add-unicode 'ᵗ' '^t' 'Modifier letter small t'
add-unicode 'ᵘ' '^u' 'Modifier letter small u'
add-unicode 'ᵛ' '^v' 'Modifier letter small v'
add-unicode 'ʷ' '^w' 'Modifier letter small w'
add-unicode 'ˣ' '^x' 'Modifier letter small x'
add-unicode 'ʸ' '^y' 'Modifier letter small y'
add-unicode 'ᶻ' '^z' 'Modifier letter small z'
add-unicode '₍' '_(' 'Subscript left parenthesis'
add-unicode '₎' '_)' 'Subscript right parenthesis'
add-unicode '₊' '_+' 'Subscript plus sign'
add-unicode '₋' '_-' 'Subscript minus'
add-unicode '₀' '_0' 'Subscript zero'
add-unicode '₁' '_1' 'Subscript one'
add-unicode '₂' '_2' 'Subscript two'
add-unicode '₃' '_3' 'Subscript three'
add-unicode '₄' '_4' 'Subscript four'
add-unicode '₅' '_5' 'Subscript five'
add-unicode '₆' '_6' 'Subscript six'
add-unicode '₇' '_7' 'Subscript seven'
add-unicode '₈' '_8' 'Subscript eight'
add-unicode '₉' '_9' 'Subscript nine'
add-unicode '₌' '_=' 'Subscript equals sign'
add-unicode 'ₐ' '_a' 'Latin subscript small letter a'
add-unicode 'ₑ' '_e' 'Latin subscript small letter e'
add-unicode 'ₕ' '_h' 'Latin subscript small letter h'
add-unicode 'ᵢ' '_i' 'Latin subscript small letter i'
add-unicode 'ⱼ' '_j' 'Latin subscript small letter j'
add-unicode 'ₖ' '_k' 'Latin subscript small letter k'
add-unicode 'ₗ' '_l' 'Latin subscript small letter l'
add-unicode 'ₘ' '_m' 'Latin subscript small letter m'
add-unicode 'ₙ' '_n' 'Latin subscript small letter n'
add-unicode 'ₒ' '_o' 'Latin subscript small letter o'
add-unicode 'ₚ' '_p' 'Latin subscript small letter p'
add-unicode 'ᵣ' '_r' 'Latin subscript small letter r'
add-unicode 'ₛ' '_s' 'Latin subscript small letter s'
add-unicode 'ₜ' '_t' 'Latin subscript small letter t'
add-unicode 'ᵤ' '_u' 'Latin subscript small letter u'
add-unicode 'ᵥ' '_v' 'Latin subscript small letter v'
add-unicode 'ₓ' '_x' 'Latin subscript small letter x'
add-unicode '—' '---' 'Em dash'
add-unicode '“' '"''' 'Left double quotation mark'
add-unicode '«' '"<' 'Left-pointing double angle quotation mark'
add-unicode '»' '">' 'Right-pointing double angle quotation mark'
add-unicode 'Ä' '"A' 'Latin capital letter a with diaeresis'
add-unicode 'Ë' '"E' 'Latin capital letter e with diaeresis'
add-unicode 'Ḧ' '"H' 'Latin capital letter h with diaeresis'
add-unicode 'Ï' '"I' 'Latin capital letter i with diaeresis'
add-unicode 'Ö' '"O' 'Latin capital letter o with diaeresis'
add-unicode 'Ü' '"U' 'Latin capital letter u with diaeresis'
add-unicode 'Ẅ' '"W' 'Latin capital letter w with diaeresis'
add-unicode 'Ẍ' '"X' 'Latin capital letter x with diaeresis'
add-unicode 'Ÿ' '"Y' 'Latin capital letter y with diaeresis'
add-unicode '„' '"`' 'Double low-9 quotation mark'
add-unicode 'ä' '"a' 'Latin small letter a with diaeresis'
add-unicode 'ë' '"e' 'Latin small letter e with diaeresis'
add-unicode 'ḧ' '"h' 'Latin small letter h with diaeresis'
add-unicode 'ï' '"i' 'Latin small letter i with diaeresis'
add-unicode 'ö' '"o' 'Latin small letter o with diaeresis'
add-unicode 'ẗ' '"t' 'Latin small letter t with diaeresis'
add-unicode 'ü' '"u' 'Latin small letter u with diaeresis'
add-unicode 'ẅ' '"w' 'Latin small letter w with diaeresis'
add-unicode 'ẍ' '"x' 'Latin small letter x with diaeresis'
add-unicode 'ÿ' '"y' 'Latin small letter y with diaeresis'
add-unicode 'Á' '''A' 'Latin capital letter a with acute'
add-unicode 'Ć' '''C' 'Latin capital letter c with acute'
add-unicode 'É' '''E' 'Latin capital letter e with acute'
add-unicode 'Ǵ' '''G' 'Latin capital letter g with acute'
add-unicode 'Í' '''I' 'Latin capital letter i with acute'
add-unicode 'Ḱ' '''K' 'Latin capital letter k with acute'
add-unicode 'Ĺ' '''L' 'Latin capital letter l with acute'
add-unicode 'Ḿ' '''M' 'Latin capital letter m with acute'
add-unicode 'Ń' '''N' 'Latin capital letter n with acute'
add-unicode 'Ó' '''O' 'Latin capital letter o with acute'
add-unicode 'Ṕ' '''P' 'Latin capital letter p with acute'
add-unicode 'Ŕ' '''R' 'Latin capital letter r with acute'
add-unicode 'Ś' '''S' 'Latin capital letter s with acute'
add-unicode 'Ú' '''U' 'Latin capital letter u with acute'
add-unicode 'Ẃ' '''W' 'Latin capital letter w with acute'
add-unicode 'Ý' '''Y' 'Latin capital letter y with acute'
add-unicode 'Ź' '''Z' 'Latin capital letter z with acute'
add-unicode 'á' '''a' 'Latin small letter a with acute'
add-unicode 'ć' '''c' 'Latin small letter c with acute'
add-unicode 'é' '''e' 'Latin small letter e with acute'
add-unicode 'ǵ' '''g' 'Latin small letter g with acute'
add-unicode 'í' '''i' 'Latin small letter i with acute'
add-unicode 'ḱ' '''k' 'Latin small letter k with acute'
add-unicode 'ĺ' '''l' 'Latin small letter l with acute'
add-unicode 'ḿ' '''m' 'Latin small letter m with acute'
add-unicode 'ń' '''n' 'Latin small letter n with acute'
add-unicode 'ó' '''o' 'Latin small letter o with acute'
add-unicode 'ṕ' '''p' 'Latin small letter p with acute'
add-unicode 'ŕ' '''r' 'Latin small letter r with acute'
add-unicode 'ś' '''s' 'Latin small letter s with acute'
add-unicode 'ú' '''u' 'Latin small letter u with acute'
add-unicode 'ẃ' '''w' 'Latin small letter w with acute'
add-unicode 'ý' '''y' 'Latin small letter y with acute'
add-unicode 'ź' '''z' 'Latin small letter z with acute'
add-unicode 'Ȧ' '.A' 'Latin capital letter a with dot above'
add-unicode 'Ḃ' '.B' 'Latin capital letter b with dot above'
add-unicode 'Ċ' '.C' 'Latin capital letter c with dot above'
add-unicode 'Ḋ' '.D' 'Latin capital letter d with dot above'
add-unicode 'Ė' '.E' 'Latin capital letter e with dot above'
add-unicode 'Ḟ' '.F' 'Latin capital letter f with dot above'
add-unicode 'Ġ' '.G' 'Latin capital letter g with dot above'
add-unicode 'Ḣ' '.H' 'Latin capital letter h with dot above'
add-unicode 'İ' '.I' 'Latin capital letter i with dot above'
add-unicode 'Ṁ' '.M' 'Latin capital letter m with dot above'
add-unicode 'Ṅ' '.N' 'Latin capital letter n with dot above'
add-unicode 'Ȯ' '.O' 'Latin capital letter o with dot above'
add-unicode 'Ṗ' '.P' 'Latin capital letter p with dot above'
add-unicode 'Ṙ' '.R' 'Latin capital letter r with dot above'
add-unicode 'Ṡ' '.S' 'Latin capital letter s with dot above'
add-unicode 'Ṫ' '.T' 'Latin capital letter t with dot above'
add-unicode 'Ẇ' '.W' 'Latin capital letter w with dot above'
add-unicode 'Ẋ' '.X' 'Latin capital letter x with dot above'
add-unicode 'Ẏ' '.Y' 'Latin capital letter y with dot above'
add-unicode 'Ż' '.Z' 'Latin capital letter z with dot above'
add-unicode 'ȧ' '.a' 'Latin small letter a with dot above'
add-unicode 'ḃ' '.b' 'Latin small letter b with dot above'
add-unicode 'ċ' '.c' 'Latin small letter c with dot above'
add-unicode 'ḋ' '.d' 'Latin small letter d with dot above'
add-unicode 'ė' '.e' 'Latin small letter e with dot above'
add-unicode 'ḟ' '.f' 'Latin small letter f with dot above'
add-unicode 'ġ' '.g' 'Latin small letter g with dot above'
add-unicode 'ḣ' '.h' 'Latin small letter h with dot above'
add-unicode 'ṁ' '.m' 'Latin small letter m with dot above'
add-unicode 'ṅ' '.n' 'Latin small letter n with dot above'
add-unicode 'ȯ' '.o' 'Latin small letter o with dot above'
add-unicode 'ṗ' '.p' 'Latin small letter p with dot above'
add-unicode 'ṙ' '.r' 'Latin small letter r with dot above'
add-unicode 'ṡ' '.s' 'Latin small letter s with dot above'
add-unicode 'ṫ' '.t' 'Latin small letter t with dot above'
add-unicode 'ẇ' '.w' 'Latin small letter w with dot above'
add-unicode 'ẋ' '.x' 'Latin small letter x with dot above'
add-unicode 'ẏ' '.y' 'Latin small letter y with dot above'
add-unicode 'ż' '.z' 'Latin small letter z with dot above'
add-unicode 'Ā' '=A' 'Latin capital letter a with macron'
add-unicode 'Ē' '=E' 'Latin capital letter e with macron'
add-unicode 'Ḡ' '=G' 'Latin capital letter g with macron'
add-unicode 'Ī' '=I' 'Latin capital letter i with macron'
add-unicode 'Ō' '=O' 'Latin capital letter o with macron'
add-unicode 'Ū' '=U' 'Latin capital letter u with macron'
add-unicode 'Ȳ' '=Y' 'Latin capital letter y with macron'
add-unicode 'ā' '=a' 'Latin small letter a with macron'
add-unicode 'ē' '=e' 'Latin small letter e with macron'
add-unicode 'ḡ' '=g' 'Latin small letter g with macron'
add-unicode 'ī' '=i' 'Latin small letter i with macron'
add-unicode 'ō' '=o' 'Latin small letter o with macron'
add-unicode 'ū' '=u' 'Latin small letter u with macron'
add-unicode 'ȳ' '=y' 'Latin small letter y with macron'
add-unicode 'Å' 'AA' 'Latin capital letter a with ring above'
add-unicode 'Æ' 'AE' 'Latin capital letter ae'
add-unicode 'Ð' 'DH' 'Latin capital letter eth'
add-unicode 'ⅅ' 'Dd' 'Double-struck italic capital d'
add-unicode 'Ő' 'HO' 'Latin capital letter o with double acute'
add-unicode 'Ű' 'HU' 'Latin capital letter u with double acute'
add-unicode 'ő' 'Ho' 'Latin small letter o with double acute'
add-unicode 'ű' 'Hu' 'Latin small letter u with double acute'
add-unicode 'ℑ' 'Im' 'Black-letter capital i'
add-unicode '⋘' 'Ll' 'Very much less-than'
add-unicode 'Œ' 'OE' 'Latin capital ligature oe'
add-unicode 'ℜ' 'Re' 'Black-letter capital r'
add-unicode 'Þ' 'TH' 'Latin capital letter thorn'
add-unicode 'ő' 'Uo' 'Latin small letter o with double acute'

# This section have all been modified from e.g. '^A' to 'A^', to not conflict with superscript characters.
# I don't understand why there's no conflict in the emacs version.
add-unicode 'Â' 'A^' 'Latin capital letter a with circumflex'
add-unicode 'Ĉ' 'C^' 'Latin capital letter c with circumflex'
add-unicode 'Ê' 'E^' 'Latin capital letter e with circumflex'
add-unicode 'Ĝ' 'G^' 'Latin capital letter g with circumflex'
add-unicode 'Ĥ' 'H^' 'Latin capital letter h with circumflex'
add-unicode 'Î' 'I^' 'Latin capital letter i with circumflex'
add-unicode 'Ĵ' 'J^' 'Latin capital letter j with circumflex'
add-unicode 'Ô' 'O^' 'Latin capital letter o with circumflex'
add-unicode 'Ŝ' 'S^' 'Latin capital letter s with circumflex'
add-unicode 'Û' 'U^' 'Latin capital letter u with circumflex'
add-unicode 'Ŵ' 'W^' 'Latin capital letter w with circumflex'
add-unicode 'Ŷ' 'Y^' 'Latin capital letter y with circumflex'
add-unicode 'Ẑ' 'Z^' 'Latin capital letter z with circumflex'
add-unicode 'â' 'a^' 'Latin small letter a with circumflex'
add-unicode 'ĉ' 'c^' 'Latin small letter c with circumflex'
add-unicode 'ê' 'e^' 'Latin small letter e with circumflex'
add-unicode 'ĝ' 'g^' 'Latin small letter g with circumflex'
add-unicode 'ĥ' 'h^' 'Latin small letter h with circumflex'
add-unicode 'î' 'i^' 'Latin small letter i with circumflex'
add-unicode 'ĵ' 'j^' 'Latin small letter j with circumflex'
add-unicode 'ô' 'o^' 'Latin small letter o with circumflex'
add-unicode 'ŝ' 's^' 'Latin small letter s with circumflex'
add-unicode 'û' 'u^' 'Latin small letter u with circumflex'
add-unicode 'ŵ' 'w^' 'Latin small letter w with circumflex'
add-unicode 'ŷ' 'y^' 'Latin small letter y with circumflex'
add-unicode 'ẑ' 'z^' 'Latin small letter z with circumflex'

add-unicode 'À' '`A' 'Latin capital letter a with grave'
add-unicode 'È' '`E' 'Latin capital letter e with grave'
add-unicode 'Ì' '`I' 'Latin capital letter i with grave'
add-unicode 'Ǹ' '`N' 'Latin capital letter n with grave'
add-unicode 'Ò' '`O' 'Latin capital letter o with grave'
add-unicode 'Ù' '`U' 'Latin capital letter u with grave'
add-unicode 'Ẁ' '`W' 'Latin capital letter w with grave'
add-unicode 'Ỳ' '`Y' 'Latin capital letter y with grave'
add-unicode 'à' '`a' 'Latin small letter a with grave'
add-unicode 'è' '`e' 'Latin small letter e with grave'
add-unicode 'ì' '`i' 'Latin small letter i with grave'
add-unicode 'ǹ' '`n' 'Latin small letter n with grave'
add-unicode 'ò' '`o' 'Latin small letter o with grave'
add-unicode 'ù' '`u' 'Latin small letter u with grave'
add-unicode 'ẁ' '`w' 'Latin small letter w with grave'
add-unicode 'ỳ' '`y' 'Latin small letter y with grave'

add-unicode-alias 'À' 'A`'
add-unicode-alias 'È' 'E`'
add-unicode-alias 'Ì' 'I`'
add-unicode-alias 'Ǹ' 'N`'
add-unicode-alias 'Ò' 'O`'
add-unicode-alias 'Ù' 'U`'
add-unicode-alias 'Ẁ' 'W`'
add-unicode-alias 'Ỳ' 'Y`'
add-unicode-alias 'à' 'a`'
add-unicode-alias 'è' 'e`'
add-unicode-alias 'ì' 'i`'
add-unicode-alias 'ǹ' 'n`'
add-unicode-alias 'ò' 'o`'
add-unicode-alias 'ù' 'u`'
add-unicode-alias 'ẁ' 'w`'
add-unicode-alias 'ỳ' 'y`' 

add-unicode 'å' 'aa' 'Latin small letter a with ring above'
add-unicode 'æ' 'ae' 'Latin small letter ae'
add-unicode 'Ç' 'cC' 'Latin capital letter c with cedilla'
add-unicode 'Ḑ' 'cD' 'Latin capital letter d with cedilla'
add-unicode 'Ȩ' 'cE' 'Latin capital letter e with cedilla'
add-unicode 'Ģ' 'cG' 'Latin capital letter g with cedilla'
add-unicode 'Ḩ' 'cH' 'Latin capital letter h with cedilla'
add-unicode 'Ķ' 'cK' 'Latin capital letter k with cedilla'
add-unicode 'Ļ' 'cL' 'Latin capital letter l with cedilla'
add-unicode 'Ņ' 'cN' 'Latin capital letter n with cedilla'
add-unicode 'Ŗ' 'cR' 'Latin capital letter r with cedilla'
add-unicode 'Ş' 'cS' 'Latin capital letter s with cedilla'
add-unicode 'Ţ' 'cT' 'Latin capital letter t with cedilla'
add-unicode 'ç' 'cc' 'Latin small letter c with cedilla'
add-unicode 'ḑ' 'cd' 'Latin small letter d with cedilla'
add-unicode 'ȩ' 'ce' 'Latin small letter e with cedilla'
add-unicode 'ģ' 'cg' 'Latin small letter g with cedilla'
add-unicode 'ḩ' 'ch' 'Latin small letter h with cedilla'
add-unicode 'ķ' 'ck' 'Latin small letter k with cedilla'
add-unicode 'ļ' 'cl' 'Latin small letter l with cedilla'
add-unicode 'ņ' 'cn' 'Latin small letter n with cedilla'
add-unicode 'ŗ' 'cr' 'Latin small letter r with cedilla'
add-unicode 'ş' 'cs' 'Latin small letter s with cedilla'
add-unicode 'ţ' 'ct' 'Latin small letter t with cedilla'
add-unicode 'ⅆ' 'dd' 'Double-struck italic small d'
add-unicode 'ð' 'dh' 'Latin small letter eth'
add-unicode 'ⅇ' 'ee' 'Double-struck italic small e'
add-unicode '≥' 'ge' 'Greater-than or equal to'
add-unicode '≫' 'gg' 'Much greater-than'
add-unicode 'ⅈ' 'ii' 'Double-struck italic small i'
add-unicode '∈' 'in' 'Element of'
add-unicode 'ⅉ' 'jj' 'Double-struck italic small j'
add-unicode 'Ą' 'kA' 'Latin capital letter a with ogonek'
add-unicode 'Ę' 'kE' 'Latin capital letter e with ogonek'
add-unicode 'Į' 'kI' 'Latin capital letter i with ogonek'
add-unicode 'Ǫ' 'kO' 'Latin capital letter o with ogonek'
add-unicode 'Ų' 'kU' 'Latin capital letter u with ogonek'
add-unicode 'ą' 'ka' 'Latin small letter a with ogonek'
add-unicode 'ę' 'ke' 'Latin small letter e with ogonek'
add-unicode 'į' 'ki' 'Latin small letter i with ogonek'
add-unicode 'ǫ' 'ko' 'Latin small letter o with ogonek'
add-unicode 'ų' 'ku' 'Latin small letter u with ogonek'
add-unicode '≤' 'le' 'Less-than or equal to'
add-unicode '≪' 'll' 'Much less-than'
add-unicode '‘' 'lq' 'Left single quotation mark'
add-unicode '∓' 'mp' 'Minus-or-plus sign'
add-unicode '≠' 'ne' 'Not equal to'
add-unicode '∋' 'ni' 'Contains as member'
add-unicode 'œ' 'oe' 'Latin small ligature oe'
add-unicode '±' 'pm' 'Plus-minus sign'
add-unicode '’' 'rq' 'Right single quotation mark'
add-unicode 'ß' 'ss' 'Latin small letter sharp s'
add-unicode 'þ' 'th' 'Latin small letter thorn'
add-unicode '→' 'to' 'Rightwards arrow'
add-unicode 'Ă' 'uA' 'Latin capital letter a with breve'
add-unicode 'Ĕ' 'uE' 'Latin capital letter e with breve'
add-unicode 'Ğ' 'uG' 'Latin capital letter g with breve'
add-unicode 'Ĭ' 'uI' 'Latin capital letter i with breve'
add-unicode 'Ŏ' 'uO' 'Latin capital letter o with breve'
add-unicode 'Ŭ' 'uU' 'Latin capital letter u with breve'
add-unicode 'ă' 'ua' 'Latin small letter a with breve'
add-unicode 'ĕ' 'ue' 'Latin small letter e with breve'
add-unicode 'ğ' 'ug' 'Latin small letter g with breve'
add-unicode 'ĭ' 'ui' 'Latin small letter i with breve'
add-unicode 'ŏ' 'uo' 'Latin small letter o with breve'
add-unicode 'ŭ' 'uu' 'Latin small letter u with breve'
add-unicode 'Ǎ' 'vA' 'Latin capital letter a with caron'
add-unicode 'Č' 'vC' 'Latin capital letter c with caron'
add-unicode 'Ď' 'vD' 'Latin capital letter d with caron'
add-unicode 'Ě' 'vE' 'Latin capital letter e with caron'
add-unicode 'Ǧ' 'vG' 'Latin capital letter g with caron'
add-unicode 'Ȟ' 'vH' 'Latin capital letter h with caron'
add-unicode 'Ǐ' 'vI' 'Latin capital letter i with caron'
add-unicode 'Ǩ' 'vK' 'Latin capital letter k with caron'
add-unicode 'Ľ' 'vL' 'Latin capital letter l with caron'
add-unicode 'Ň' 'vN' 'Latin capital letter n with caron'
add-unicode 'Ǒ' 'vO' 'Latin capital letter o with caron'
add-unicode 'Ř' 'vR' 'Latin capital letter r with caron'
add-unicode 'Š' 'vS' 'Latin capital letter s with caron'
add-unicode 'Ť' 'vT' 'Latin capital letter t with caron'
add-unicode 'Ǔ' 'vU' 'Latin capital letter u with caron'
add-unicode 'Ž' 'vZ' 'Latin capital letter z with caron'
add-unicode 'ǎ' 'va' 'Latin small letter a with caron'
add-unicode 'č' 'vc' 'Latin small letter c with caron'
add-unicode 'ď' 'vd' 'Latin small letter d with caron'
add-unicode 'ě' 've' 'Latin small letter e with caron'
add-unicode 'ǧ' 'vg' 'Latin small letter g with caron'
add-unicode 'ȟ' 'vh' 'Latin small letter h with caron'
add-unicode 'ǐ' 'vi' 'Latin small letter i with caron'
add-unicode 'ǰ' 'vj' 'Latin small letter j with caron'
add-unicode 'ǩ' 'vk' 'Latin small letter k with caron'
add-unicode 'ľ' 'vl' 'Latin small letter l with caron'
add-unicode 'ň' 'vn' 'Latin small letter n with caron'
add-unicode 'ǒ' 'vo' 'Latin small letter o with caron'
add-unicode 'ř' 'vr' 'Latin small letter r with caron'
add-unicode 'š' 'vs' 'Latin small letter s with caron'
add-unicode 'ť' 'vt' 'Latin small letter t with caron'
add-unicode 'ǔ' 'vu' 'Latin small letter u with caron'
add-unicode 'ž' 'vz' 'Latin small letter z with caron'
add-unicode '℘' 'wp' 'Script capital p'
add-unicode '≀' 'wr' 'Wreath product'

add-unicode 'Ã' '~A' 'Latin capital letter a with tilde'
add-unicode 'Ẽ' '~E' 'Latin capital letter e with tilde'
add-unicode 'Ĩ' '~I' 'Latin capital letter i with tilde'
add-unicode 'Ñ' '~N' 'Latin capital letter n with tilde'
add-unicode 'Õ' '~O' 'Latin capital letter o with tilde'
add-unicode 'Ũ' '~U' 'Latin capital letter u with tilde'
add-unicode 'Ṽ' '~V' 'Latin capital letter v with tilde'
add-unicode 'Ỹ' '~Y' 'Latin capital letter y with tilde'
add-unicode 'ã' '~a' 'Latin small letter a with tilde'
add-unicode 'ẽ' '~e' 'Latin small letter e with tilde'
add-unicode 'ĩ' '~i' 'Latin small letter i with tilde'
add-unicode 'ñ' '~n' 'Latin small letter n with tilde'
add-unicode 'õ' '~o' 'Latin small letter o with tilde'
add-unicode 'ũ' '~u' 'Latin small letter u with tilde'
add-unicode 'ṽ' '~v' 'Latin small letter v with tilde'
add-unicode 'ỹ' '~y' 'Latin small letter y with tilde'

add-unicode-alias 'Ã' 'A~'
add-unicode-alias 'Ẽ' 'E~'
add-unicode-alias 'Ĩ' 'I~'
add-unicode-alias 'Ñ' 'N~'
add-unicode-alias 'Õ' 'O~'
add-unicode-alias 'Ũ' 'U~'
add-unicode-alias 'Ṽ' 'V~'
add-unicode-alias 'Ỹ' 'Y~'
add-unicode-alias 'ã' 'a~'
add-unicode-alias 'ẽ' 'e~'
add-unicode-alias 'ĩ' 'i~'
add-unicode-alias 'ñ' 'n~'
add-unicode-alias 'õ' 'o~'
add-unicode-alias 'ũ' 'u~'
add-unicode-alias 'ṽ' 'v~'
add-unicode-alias 'ỹ' 'y~' 

add-unicode 'º' '^o_' 'Masculine ordinal indicator'
add-unicode 'ª' '^a_' 'Feminine ordinal indicator'
add-unicode '¨' '"{}' 'Diaeresis'
add-unicode 'Ǿ' '''\O' 'Latin capital letter o with stroke and acute'
add-unicode 'ǿ' '''\o' 'Latin small letter o with stroke and acute'
add-unicode '´' '''{}' 'Acute accent'
add-unicode '˙' '.{}' 'Dot above'
add-unicode '¯' '={}' 'Macron'
add-unicode '□' 'Box' 'White square'
add-unicode '⋒' 'Cap' 'Double intersection'
add-unicode '⋓' 'Cup' 'Double union'
add-unicode 'Ϯ' 'Dei' 'Coptic capital letter dei'
add-unicode 'Ϥ' 'Fei' 'Coptic capital letter fei'
add-unicode '˝' 'H{}' 'Double acute accent'
add-unicode '↰' 'Lsh' 'Upwards arrow with tip leftwards'
add-unicode '↱' 'Rsh' 'Upwards arrow with tip rightwards'
add-unicode '∗' 'ast' 'Asterisk operator'
add-unicode '⊥' 'bot' 'Up tack'
add-unicode '⟨' 'bra' 'Mathematical left angle bracket'
add-unicode '∩' 'cap' 'Intersection'
add-unicode '∪' 'cup' 'Union'
add-unicode '¸' 'c{}' 'Cedilla'
add-unicode '†' 'dag' 'Dagger'
add-unicode 'ϯ' 'dei' 'Coptic small letter dei'
add-unicode '÷' 'div' 'Division sign'
add-unicode 'ℓ' 'ell' 'Script small l'
add-unicode '〗' 'end' 'Right white lenticular bracket'
add-unicode 'ϥ' 'fei' 'Coptic small letter fei'
add-unicode '‹' 'flq' 'Single left-pointing angle quotation mark'
add-unicode '›' 'frq' 'Single right-pointing angle quotation mark'
# add-unicode '≥' 'geq' 'Greater-than or equal to'
add-unicode '⋙' 'ggg' 'Very much greater-than'
add-unicode '‚' 'glq' 'Single low-9 quotation mark'
add-unicode '‘' 'grq' 'Left single quotation mark'
add-unicode '⇔' 'iff' 'Left right double arrow'
add-unicode '∫' 'int' 'Integral'
add-unicode '₭' 'kip' 'Kip sign'
add-unicode '˛' 'k{}' 'Ogonek'
add-unicode '“' 'ldq' 'Left double quotation mark'
# add-unicode '≤' 'leq' 'Less-than or equal to'
add-unicode '◁' 'lhd' 'White left-pointing triangle'
add-unicode '⋘' 'lll' 'Very much less-than'
add-unicode '℧' 'mho' 'Inverted ohm sign'
add-unicode '∣' 'mid' 'Divides'
add-unicode '¬' 'neg' 'Not sign'
add-unicode '≠' 'neq' 'Not equal to'
add-unicode '̸' 'not' 'Combining long solidus overlay'
add-unicode 'Ω' 'ohm' 'Ohm sign'
# add-unicode ' ' 'par' ''
add-unicode '⅌' 'per' 'Per sign'
add-unicode '∎' 'qed' 'End of proof'
add-unicode '”' 'rdq' 'Right double quotation mark'
add-unicode '▷' 'rhd' 'White right-pointing triangle'
add-unicode '﹨' 'sbs' 'Small reverse solidus'
add-unicode '∼' 'sim' 'Tilde operator'
add-unicode '⃀' 'som' ''
add-unicode '∑' 'sum' 'N-ary summation'
add-unicode '⊤' 'top' 'Down tack'
add-unicode '˘' 'u{}' 'Breve'
add-unicode '∨' 'vee' 'Logical or'
add-unicode 'ˇ' 'v{}' 'Caron'
add-unicode '₩' 'won' 'Won sign'
add-unicode '¥' 'yen' 'Yen sign'
add-unicode '˜' '~{}' 'Small tilde'
add-unicode 'ᴭ' '^\Ae' 'Modifier letter capital ae'
add-unicode 'ᴽ' '^\Ou' 'Modifier letter capital ou'
add-unicode '𐞃' '^\ae' ''
add-unicode 'Ḯ' '"\''I' 'Latin capital letter i with diaeresis and acute'
add-unicode 'Ǘ' '"\''U' 'Latin capital letter u with diaeresis and acute'
add-unicode 'ḯ' '"\''i' 'Latin small letter i with diaeresis and acute'
add-unicode 'ǘ' '"\''u' 'Latin small letter u with diaeresis and acute'
add-unicode 'Ǟ' '"\=A' 'Latin capital letter a with diaeresis and macron'
add-unicode 'Ȫ' '"\=O' 'Latin capital letter o with diaeresis and macron'
add-unicode 'Ǖ' '"\=U' 'Latin capital letter u with diaeresis and macron'
add-unicode 'ǟ' '"\=a' 'Latin small letter a with diaeresis and macron'
add-unicode 'ȫ' '"\=o' 'Latin small letter o with diaeresis and macron'
add-unicode 'ǖ' '"\=u' 'Latin small letter u with diaeresis and macron'
add-unicode 'Ǜ' '"\`U' 'Latin capital letter u with diaeresis and grave'
add-unicode 'ǜ' '"\`u' 'Latin small letter u with diaeresis and grave'
add-unicode 'Ǚ' '"\vU' 'Latin capital letter u with diaeresis and caron'
add-unicode 'ǚ' '"\vu' 'Latin small letter u with diaeresis and caron'
add-unicode 'Ä' '"{A}' 'Latin capital letter a with diaeresis'
add-unicode 'Ë' '"{E}' 'Latin capital letter e with diaeresis'
add-unicode 'Ḧ' '"{H}' 'Latin capital letter h with diaeresis'
add-unicode 'Ï' '"{I}' 'Latin capital letter i with diaeresis'
add-unicode 'Ö' '"{O}' 'Latin capital letter o with diaeresis'
add-unicode 'Ü' '"{U}' 'Latin capital letter u with diaeresis'
add-unicode 'Ẅ' '"{W}' 'Latin capital letter w with diaeresis'
add-unicode 'Ẍ' '"{X}' 'Latin capital letter x with diaeresis'
add-unicode 'Ÿ' '"{Y}' 'Latin capital letter y with diaeresis'
add-unicode 'ä' '"{a}' 'Latin small letter a with diaeresis'
add-unicode 'ë' '"{e}' 'Latin small letter e with diaeresis'
add-unicode 'ḧ' '"{h}' 'Latin small letter h with diaeresis'
add-unicode 'ï' '"{i}' 'Latin small letter i with diaeresis'
add-unicode 'ö' '"{o}' 'Latin small letter o with diaeresis'
add-unicode 'ẗ' '"{t}' 'Latin small letter t with diaeresis'
add-unicode 'ü' '"{u}' 'Latin small letter u with diaeresis'
add-unicode 'ẅ' '"{w}' 'Latin small letter w with diaeresis'
add-unicode 'ẍ' '"{x}' 'Latin small letter x with diaeresis'
add-unicode 'ÿ' '"{y}' 'Latin small letter y with diaeresis'
add-unicode 'Ṥ' '''\.S' 'Latin capital letter s with acute and dot above'
add-unicode 'ṥ' '''\.s' 'Latin small letter s with acute and dot above'
add-unicode 'Ǽ' '''\AE' 'Latin capital letter ae with acute'
add-unicode 'ǽ' '''\ae' 'Latin small letter ae with acute'
add-unicode 'Á' '''{A}' 'Latin capital letter a with acute'
add-unicode 'Ć' '''{C}' 'Latin capital letter c with acute'
add-unicode 'É' '''{E}' 'Latin capital letter e with acute'
add-unicode 'Ǵ' '''{G}' 'Latin capital letter g with acute'
add-unicode 'Í' '''{I}' 'Latin capital letter i with acute'
add-unicode 'Ḱ' '''{K}' 'Latin capital letter k with acute'
add-unicode 'Ĺ' '''{L}' 'Latin capital letter l with acute'
add-unicode 'Ḿ' '''{M}' 'Latin capital letter m with acute'
add-unicode 'Ń' '''{N}' 'Latin capital letter n with acute'
add-unicode 'Ó' '''{O}' 'Latin capital letter o with acute'
add-unicode 'Ṕ' '''{P}' 'Latin capital letter p with acute'
add-unicode 'Ŕ' '''{R}' 'Latin capital letter r with acute'
add-unicode 'Ś' '''{S}' 'Latin capital letter s with acute'
add-unicode 'Ú' '''{U}' 'Latin capital letter u with acute'
add-unicode 'Ẃ' '''{W}' 'Latin capital letter w with acute'
add-unicode 'Ý' '''{Y}' 'Latin capital letter y with acute'
add-unicode 'Ź' '''{Z}' 'Latin capital letter z with acute'
add-unicode 'á' '''{a}' 'Latin small letter a with acute'
add-unicode 'ć' '''{c}' 'Latin small letter c with acute'
add-unicode 'é' '''{e}' 'Latin small letter e with acute'
add-unicode 'ǵ' '''{g}' 'Latin small letter g with acute'
add-unicode 'í' '''{i}' 'Latin small letter i with acute'
add-unicode 'ḱ' '''{k}' 'Latin small letter k with acute'
add-unicode 'ĺ' '''{l}' 'Latin small letter l with acute'
add-unicode 'ḿ' '''{m}' 'Latin small letter m with acute'
add-unicode 'ń' '''{n}' 'Latin small letter n with acute'
add-unicode 'ó' '''{o}' 'Latin small letter o with acute'
add-unicode 'ṕ' '''{p}' 'Latin small letter p with acute'
add-unicode 'ŕ' '''{r}' 'Latin small letter r with acute'
add-unicode 'ś' '''{s}' 'Latin small letter s with acute'
add-unicode 'ú' '''{u}' 'Latin small letter u with acute'
add-unicode 'ẃ' '''{w}' 'Latin small letter w with acute'
add-unicode 'ý' '''{y}' 'Latin small letter y with acute'
add-unicode 'ź' '''{z}' 'Latin small letter z with acute'
add-unicode 'Ǡ' '.\=A' 'Latin capital letter a with dot above and macron'
add-unicode 'Ȱ' '.\=O' 'Latin capital letter o with dot above and macron'
add-unicode 'ǡ' '.\=a' 'Latin small letter a with dot above and macron'
add-unicode 'ȱ' '.\=o' 'Latin small letter o with dot above and macron'
add-unicode 'Ȧ' '.{A}' 'Latin capital letter a with dot above'
add-unicode 'Ḃ' '.{B}' 'Latin capital letter b with dot above'
add-unicode 'Ċ' '.{C}' 'Latin capital letter c with dot above'
add-unicode 'Ḋ' '.{D}' 'Latin capital letter d with dot above'
add-unicode 'Ė' '.{E}' 'Latin capital letter e with dot above'
add-unicode 'Ḟ' '.{F}' 'Latin capital letter f with dot above'
add-unicode 'Ġ' '.{G}' 'Latin capital letter g with dot above'
add-unicode 'Ḣ' '.{H}' 'Latin capital letter h with dot above'
add-unicode 'İ' '.{I}' 'Latin capital letter i with dot above'
add-unicode 'Ṁ' '.{M}' 'Latin capital letter m with dot above'
add-unicode 'Ṅ' '.{N}' 'Latin capital letter n with dot above'
add-unicode 'Ȯ' '.{O}' 'Latin capital letter o with dot above'
add-unicode 'Ṗ' '.{P}' 'Latin capital letter p with dot above'
add-unicode 'Ṙ' '.{R}' 'Latin capital letter r with dot above'
add-unicode 'Ṡ' '.{S}' 'Latin capital letter s with dot above'
add-unicode 'Ṫ' '.{T}' 'Latin capital letter t with dot above'
add-unicode 'Ẇ' '.{W}' 'Latin capital letter w with dot above'
add-unicode 'Ẋ' '.{X}' 'Latin capital letter x with dot above'
add-unicode 'Ẏ' '.{Y}' 'Latin capital letter y with dot above'
add-unicode 'Ż' '.{Z}' 'Latin capital letter z with dot above'
add-unicode 'ȧ' '.{a}' 'Latin small letter a with dot above'
add-unicode 'ḃ' '.{b}' 'Latin small letter b with dot above'
add-unicode 'ċ' '.{c}' 'Latin small letter c with dot above'
add-unicode 'ḋ' '.{d}' 'Latin small letter d with dot above'
add-unicode 'ė' '.{e}' 'Latin small letter e with dot above'
add-unicode 'ḟ' '.{f}' 'Latin small letter f with dot above'
add-unicode 'ġ' '.{g}' 'Latin small letter g with dot above'
add-unicode 'ḣ' '.{h}' 'Latin small letter h with dot above'
add-unicode 'ṁ' '.{m}' 'Latin small letter m with dot above'
add-unicode 'ṅ' '.{n}' 'Latin small letter n with dot above'
add-unicode 'ȯ' '.{o}' 'Latin small letter o with dot above'
add-unicode 'ṗ' '.{p}' 'Latin small letter p with dot above'
add-unicode 'ṙ' '.{r}' 'Latin small letter r with dot above'
add-unicode 'ṡ' '.{s}' 'Latin small letter s with dot above'
add-unicode 'ṫ' '.{t}' 'Latin small letter t with dot above'
add-unicode 'ẇ' '.{w}' 'Latin small letter w with dot above'
add-unicode 'ẋ' '.{x}' 'Latin small letter x with dot above'
add-unicode 'ẏ' '.{y}' 'Latin small letter y with dot above'
add-unicode 'ż' '.{z}' 'Latin small letter z with dot above'
add-unicode 'Ṻ' '=\"U' 'Latin capital letter u with macron and diaeresis'
add-unicode 'ṻ' '=\"u' 'Latin small letter u with macron and diaeresis'
add-unicode 'Ḗ' '=\''E' 'Latin capital letter e with macron and acute'
add-unicode 'Ṓ' '=\''O' 'Latin capital letter o with macron and acute'
add-unicode 'ḗ' '=\''e' 'Latin small letter e with macron and acute'
add-unicode 'ṓ' '=\''o' 'Latin small letter o with macron and acute'
add-unicode 'Ǣ' '=\AE' 'Latin capital letter ae with macron'
add-unicode 'Ḕ' '=\`E' 'Latin capital letter e with macron and grave'
add-unicode 'Ṑ' '=\`O' 'Latin capital letter o with macron and grave'
add-unicode 'ḕ' '=\`e' 'Latin small letter e with macron and grave'
add-unicode 'ṑ' '=\`o' 'Latin small letter o with macron and grave'
add-unicode 'ǣ' '=\ae' 'Latin small letter ae with macron'
add-unicode 'Ā' '={A}' 'Latin capital letter a with macron'
add-unicode 'Ē' '={E}' 'Latin capital letter e with macron'
add-unicode 'Ḡ' '={G}' 'Latin capital letter g with macron'
add-unicode 'Ī' '={I}' 'Latin capital letter i with macron'
add-unicode 'Ō' '={O}' 'Latin capital letter o with macron'
add-unicode 'Ū' '={U}' 'Latin capital letter u with macron'
add-unicode 'Ȳ' '={Y}' 'Latin capital letter y with macron'
add-unicode 'ā' '={a}' 'Latin small letter a with macron'
add-unicode 'ē' '={e}' 'Latin small letter e with macron'
add-unicode 'ḡ' '={g}' 'Latin small letter g with macron'
add-unicode 'ī' '={i}' 'Latin small letter i with macron'
add-unicode 'ō' '={o}' 'Latin small letter o with macron'
add-unicode 'ū' '={u}' 'Latin small letter u with macron'
add-unicode 'ȳ' '={y}' 'Latin small letter y with macron'
add-unicode 'Ϩ' 'Hori' 'Coptic capital letter hori'
add-unicode 'Ő' 'H{O}' 'Latin capital letter o with double acute'
add-unicode 'Ű' 'H{U}' 'Latin capital letter u with double acute'
add-unicode 'ő' 'H{o}' 'Latin small letter o with double acute'
add-unicode 'ű' 'H{u}' 'Latin small letter u with double acute'
add-unicode '⋈' 'Join' 'Bowtie'
add-unicode 'Ϧ' 'Khei' 'Coptic capital letter khei'
add-unicode 'Ϣ' 'Shei' 'Coptic capital letter shei'
add-unicode 'ő' 'U{o}' 'Latin small letter o with double acute'
add-unicode '‖' 'Vert' 'Double vertical line'
add-unicode 'Ấ' '^\''A' 'Latin capital letter a with circumflex and acute'
add-unicode 'Ế' '^\''E' 'Latin capital letter e with circumflex and acute'
add-unicode 'Ố' '^\''O' 'Latin capital letter o with circumflex and acute'
add-unicode 'ấ' '^\''a' 'Latin small letter a with circumflex and acute'
add-unicode 'ế' '^\''e' 'Latin small letter e with circumflex and acute'
add-unicode 'ố' '^\''o' 'Latin small letter o with circumflex and acute'
add-unicode 'Ầ' '^\`A' 'Latin capital letter a with circumflex and grave'
add-unicode 'Ề' '^\`E' 'Latin capital letter e with circumflex and grave'
add-unicode 'Ồ' '^\`O' 'Latin capital letter o with circumflex and grave'
add-unicode 'ầ' '^\`a' 'Latin small letter a with circumflex and grave'
add-unicode 'ề' '^\`e' 'Latin small letter e with circumflex and grave'
add-unicode 'ồ' '^\`o' 'Latin small letter o with circumflex and grave'
add-unicode 'Ẫ' '^\~A' 'Latin capital letter a with circumflex and tilde'
add-unicode 'Ễ' '^\~E' 'Latin capital letter e with circumflex and tilde'
add-unicode 'Ỗ' '^\~O' 'Latin capital letter o with circumflex and tilde'
add-unicode 'ẫ' '^\~a' 'Latin small letter a with circumflex and tilde'
add-unicode 'ễ' '^\~e' 'Latin small letter e with circumflex and tilde'
add-unicode 'ỗ' '^\~o' 'Latin small letter o with circumflex and tilde'
add-unicode 'Â' '^{A}' 'Latin capital letter a with circumflex'
add-unicode 'Ĉ' '^{C}' 'Latin capital letter c with circumflex'
add-unicode 'Ê' '^{E}' 'Latin capital letter e with circumflex'
add-unicode 'Ĝ' '^{G}' 'Latin capital letter g with circumflex'
add-unicode 'Ĥ' '^{H}' 'Latin capital letter h with circumflex'
add-unicode 'Î' '^{I}' 'Latin capital letter i with circumflex'
add-unicode 'Ĵ' '^{J}' 'Latin capital letter j with circumflex'
add-unicode 'Ô' '^{O}' 'Latin capital letter o with circumflex'
add-unicode 'Ŝ' '^{S}' 'Latin capital letter s with circumflex'
add-unicode 'Û' '^{U}' 'Latin capital letter u with circumflex'
add-unicode 'Ŵ' '^{W}' 'Latin capital letter w with circumflex'
add-unicode 'Ŷ' '^{Y}' 'Latin capital letter y with circumflex'
add-unicode 'Ẑ' '^{Z}' 'Latin capital letter z with circumflex'
add-unicode 'â' '^{a}' 'Latin small letter a with circumflex'
add-unicode 'ĉ' '^{c}' 'Latin small letter c with circumflex'
add-unicode 'ê' '^{e}' 'Latin small letter e with circumflex'
add-unicode 'ĝ' '^{g}' 'Latin small letter g with circumflex'
add-unicode 'ĥ' '^{h}' 'Latin small letter h with circumflex'
add-unicode 'î' '^{i}' 'Latin small letter i with circumflex'
add-unicode 'ĵ' '^{j}' 'Latin small letter j with circumflex'
add-unicode 'ô' '^{o}' 'Latin small letter o with circumflex'
add-unicode 'ŝ' '^{s}' 'Latin small letter s with circumflex'
add-unicode 'û' '^{u}' 'Latin small letter u with circumflex'
add-unicode 'ŵ' '^{w}' 'Latin small letter w with circumflex'
add-unicode 'ŷ' '^{y}' 'Latin small letter y with circumflex'
add-unicode 'ẑ' '^{z}' 'Latin small letter z with circumflex'
add-unicode 'À' '`{A}' 'Latin capital letter a with grave'
add-unicode 'È' '`{E}' 'Latin capital letter e with grave'
add-unicode 'Ì' '`{I}' 'Latin capital letter i with grave'
add-unicode 'Ǹ' '`{N}' 'Latin capital letter n with grave'
add-unicode 'Ò' '`{O}' 'Latin capital letter o with grave'
add-unicode 'Ù' '`{U}' 'Latin capital letter u with grave'
add-unicode 'Ẁ' '`{W}' 'Latin capital letter w with grave'
add-unicode 'Ỳ' '`{Y}' 'Latin capital letter y with grave'
add-unicode 'à' '`{a}' 'Latin small letter a with grave'
add-unicode 'è' '`{e}' 'Latin small letter e with grave'
add-unicode 'ì' '`{i}' 'Latin small letter i with grave'
add-unicode 'ǹ' '`{n}' 'Latin small letter n with grave'
add-unicode 'ò' '`{o}' 'Latin small letter o with grave'
add-unicode 'ù' '`{u}' 'Latin small letter u with grave'
add-unicode 'ẁ' '`{w}' 'Latin small letter w with grave'
add-unicode 'ỳ' '`{y}' 'Latin small letter y with grave'
add-unicode '¦' 'atop' 'Broken bar'
add-unicode 'ℶ' 'beth' 'Bet symbol'
add-unicode 'Ḉ' 'c\''C' 'Latin capital letter c with cedilla and acute'
add-unicode 'ḉ' 'c\''c' 'Latin small letter c with cedilla and acute'
add-unicode 'Ḝ' 'c\uE' 'Latin capital letter e with cedilla and breve'
add-unicode 'ḝ' 'c\ue' 'Latin small letter e with cedilla and breve'
add-unicode '·' 'cdot' 'Middle dot'
add-unicode '₵' 'cedi' 'Cedi sign'
add-unicode '¢' 'cent' 'Cent sign'
add-unicode '∘' 'circ' 'Ring operator'
add-unicode '≅' 'cong' 'Approximately equal to'
add-unicode 'Ç' 'c{C}' 'Latin capital letter c with cedilla'
add-unicode 'Ḑ' 'c{D}' 'Latin capital letter d with cedilla'
add-unicode 'Ȩ' 'c{E}' 'Latin capital letter e with cedilla'
add-unicode 'Ģ' 'c{G}' 'Latin capital letter g with cedilla'
add-unicode 'Ḩ' 'c{H}' 'Latin capital letter h with cedilla'
add-unicode 'Ķ' 'c{K}' 'Latin capital letter k with cedilla'
add-unicode 'Ļ' 'c{L}' 'Latin capital letter l with cedilla'
add-unicode 'Ņ' 'c{N}' 'Latin capital letter n with cedilla'
add-unicode 'Ŗ' 'c{R}' 'Latin capital letter r with cedilla'
add-unicode 'Ş' 'c{S}' 'Latin capital letter s with cedilla'
add-unicode 'Ţ' 'c{T}' 'Latin capital letter t with cedilla'
add-unicode 'ç' 'c{c}' 'Latin small letter c with cedilla'
add-unicode 'ḑ' 'c{d}' 'Latin small letter d with cedilla'
add-unicode 'ȩ' 'c{e}' 'Latin small letter e with cedilla'
add-unicode 'ģ' 'c{g}' 'Latin small letter g with cedilla'
add-unicode 'ḩ' 'c{h}' 'Latin small letter h with cedilla'
add-unicode 'ķ' 'c{k}' 'Latin small letter k with cedilla'
add-unicode 'ļ' 'c{l}' 'Latin small letter l with cedilla'
add-unicode 'ņ' 'c{n}' 'Latin small letter n with cedilla'
add-unicode 'ŗ' 'c{r}' 'Latin small letter r with cedilla'
add-unicode 'ş' 'c{s}' 'Latin small letter s with cedilla'
add-unicode 'ţ' 'c{t}' 'Latin small letter t with cedilla'
add-unicode 'Ṩ' 'd\.S' 'Latin capital letter s with dot below and dot above'
add-unicode 'ṩ' 'd\.s' 'Latin small letter s with dot below and dot above'
add-unicode 'Ḹ' 'd\=L' 'Latin capital letter l with dot below and macron'
add-unicode 'Ṝ' 'd\=R' 'Latin capital letter r with dot below and macron'
add-unicode 'ḹ' 'd\=l' 'Latin small letter l with dot below and macron'
add-unicode 'ṝ' 'd\=r' 'Latin small letter r with dot below and macron'
add-unicode '‡' 'ddag' 'Double dagger'
add-unicode '≙' 'defs' 'Estimates'
add-unicode '₫' 'dong' 'Dong sign'
add-unicode 'Ạ' 'd{A}' 'Latin capital letter a with dot below'
add-unicode 'Ḅ' 'd{B}' 'Latin capital letter b with dot below'
add-unicode 'Ḍ' 'd{D}' 'Latin capital letter d with dot below'
add-unicode 'Ẹ' 'd{E}' 'Latin capital letter e with dot below'
add-unicode 'Ḥ' 'd{H}' 'Latin capital letter h with dot below'
add-unicode 'Ị' 'd{I}' 'Latin capital letter i with dot below'
add-unicode 'Ḳ' 'd{K}' 'Latin capital letter k with dot below'
add-unicode 'Ḷ' 'd{L}' 'Latin capital letter l with dot below'
add-unicode 'Ṃ' 'd{M}' 'Latin capital letter m with dot below'
add-unicode 'Ṇ' 'd{N}' 'Latin capital letter n with dot below'
add-unicode 'Ọ' 'd{O}' 'Latin capital letter o with dot below'
add-unicode 'Ṛ' 'd{R}' 'Latin capital letter r with dot below'
add-unicode 'Ṣ' 'd{S}' 'Latin capital letter s with dot below'
add-unicode 'Ṭ' 'd{T}' 'Latin capital letter t with dot below'
add-unicode 'Ụ' 'd{U}' 'Latin capital letter u with dot below'
add-unicode 'Ṿ' 'd{V}' 'Latin capital letter v with dot below'
add-unicode 'Ẉ' 'd{W}' 'Latin capital letter w with dot below'
add-unicode 'Ỵ' 'd{Y}' 'Latin capital letter y with dot below'
add-unicode 'Ẓ' 'd{Z}' 'Latin capital letter z with dot below'
add-unicode 'ạ' 'd{a}' 'Latin small letter a with dot below'
add-unicode 'ḅ' 'd{b}' 'Latin small letter b with dot below'
add-unicode 'ḍ' 'd{d}' 'Latin small letter d with dot below'
add-unicode 'ẹ' 'd{e}' 'Latin small letter e with dot below'
add-unicode 'ḥ' 'd{h}' 'Latin small letter h with dot below'
add-unicode 'ị' 'd{i}' 'Latin small letter i with dot below'
add-unicode 'ḳ' 'd{k}' 'Latin small letter k with dot below'
add-unicode 'ḷ' 'd{l}' 'Latin small letter l with dot below'
add-unicode 'ṃ' 'd{m}' 'Latin small letter m with dot below'
add-unicode 'ṇ' 'd{n}' 'Latin small letter n with dot below'
add-unicode 'ọ' 'd{o}' 'Latin small letter o with dot below'
add-unicode 'ṛ' 'd{r}' 'Latin small letter r with dot below'
add-unicode 'ṣ' 'd{s}' 'Latin small letter s with dot below'
add-unicode 'ṭ' 'd{t}' 'Latin small letter t with dot below'
add-unicode 'ụ' 'd{u}' 'Latin small letter u with dot below'
add-unicode 'ṿ' 'd{v}' 'Latin small letter v with dot below'
add-unicode 'ẉ' 'd{w}' 'Latin small letter w with dot below'
add-unicode 'ỵ' 'd{y}' 'Latin small letter y with dot below'
add-unicode 'ẓ' 'd{z}' 'Latin small letter z with dot below'
add-unicode '€' 'euro' 'Euro sign'
add-unicode '♭' 'flat' 'Music flat sign'
add-unicode '«' 'flqq' 'Left-pointing double angle quotation mark'
add-unicode '»' 'frqq' 'Right-pointing double angle quotation mark'
add-unicode '≧' 'geqq' 'Greater-than over equal to'
add-unicode '←' 'gets' 'Leftwards arrow'
add-unicode '„' 'glqq' 'Double low-9 quotation mark'
add-unicode '≩' 'gneq' 'Greater-than but not equal to'
add-unicode '“' 'grqq' 'Left double quotation mark'
add-unicode 'ℏ' 'hbar' 'Planck constant over two pi'
add-unicode 'ϩ' 'hori' 'Coptic small letter hori'
add-unicode '∬' 'iint' 'Double integral'
add-unicode 'Ǭ' 'k\=O' 'Latin capital letter o with ogonek and macron'
add-unicode 'ǭ' 'k\=o' 'Latin small letter o with ogonek and macron'
add-unicode 'ϧ' 'khei' 'Coptic small letter khei'
add-unicode 'Ą' 'k{A}' 'Latin capital letter a with ogonek'
add-unicode 'Ę' 'k{E}' 'Latin capital letter e with ogonek'
add-unicode 'Į' 'k{I}' 'Latin capital letter i with ogonek'
add-unicode 'Ǫ' 'k{O}' 'Latin capital letter o with ogonek'
add-unicode 'Ų' 'k{U}' 'Latin capital letter u with ogonek'
add-unicode 'ą' 'k{a}' 'Latin small letter a with ogonek'
add-unicode 'ę' 'k{e}' 'Latin small letter e with ogonek'
add-unicode 'į' 'k{i}' 'Latin small letter i with ogonek'
add-unicode 'ǫ' 'k{o}' 'Latin small letter o with ogonek'
add-unicode 'ų' 'k{u}' 'Latin small letter u with ogonek'
add-unicode '₾' 'lari' 'Lari sign'
add-unicode '∕' 'ldiv' 'Division slash'
add-unicode '≦' 'leqq' 'Less-than over equal to'
add-unicode '₤' 'lira' 'Lira sign'
add-unicode '≨' 'lneq' 'Less-than but not equal to'
add-unicode '¬' 'lnot' 'Not sign'
add-unicode '♂' 'male' 'Male sign'
add-unicode '₥' 'mill' 'Mill sign'
add-unicode '≱' 'ngeq' 'Neither greater-than nor equal to'
add-unicode '≯' 'ngtr' 'Not greater-than'
add-unicode '≰' 'nleq' 'Neither less-than nor equal to'
add-unicode '∤' 'nmid' 'Does not divide'
add-unicode '≁' 'nsim' 'Not tilde'
add-unicode '⊙' 'odot' 'Circled dot operator'
add-unicode '∮' 'oint' 'Contour integral'
add-unicode '⊥' 'perp' 'Up tack'
add-unicode '₱' 'peso' 'Peso sign'
add-unicode '≺' 'prec' 'Precedes'
add-unicode '∏' 'prod' 'N-ary product'
add-unicode '∜' 'qdrt' 'Fourth root'
add-unicode ' ' 'quad' 'Em quad'
add-unicode '▭' 'rect' 'White rectangle'
add-unicode '﷼' 'rial' 'Rial sign'
add-unicode '⁄' 'sdiv' 'Fraction slash'
add-unicode 'ϣ' 'shei' 'Coptic small letter shei'
add-unicode '√' 'sqrt' 'Square root'
add-unicode '⋆' 'star' 'Star operator'
add-unicode '≻' 'succ' 'Succeeds'
add-unicode '√' 'surd' 'Square root'
add-unicode 'Ắ' 'u\''A' 'Latin capital letter a with breve and acute'
add-unicode 'ắ' 'u\''a' 'Latin small letter a with breve and acute'
add-unicode 'Ằ' 'u\`A' 'Latin capital letter a with breve and grave'
add-unicode 'ằ' 'u\`a' 'Latin small letter a with breve and grave'
add-unicode 'Ẵ' 'u\~A' 'Latin capital letter a with breve and tilde'
add-unicode 'ẵ' 'u\~a' 'Latin small letter a with breve and tilde'
add-unicode 'Ă' 'u{A}' 'Latin capital letter a with breve'
add-unicode 'Ĕ' 'u{E}' 'Latin capital letter e with breve'
add-unicode 'Ğ' 'u{G}' 'Latin capital letter g with breve'
add-unicode 'Ĭ' 'u{I}' 'Latin capital letter i with breve'
add-unicode 'Ŏ' 'u{O}' 'Latin capital letter o with breve'
add-unicode 'Ŭ' 'u{U}' 'Latin capital letter u with breve'
add-unicode 'ă' 'u{a}' 'Latin small letter a with breve'
add-unicode 'ĕ' 'u{e}' 'Latin small letter e with breve'
add-unicode 'ğ' 'u{g}' 'Latin small letter g with breve'
add-unicode 'ĭ' 'u{i}' 'Latin small letter i with breve'
add-unicode 'ŏ' 'u{o}' 'Latin small letter o with breve'
add-unicode 'ŭ' 'u{u}' 'Latin small letter u with breve'
add-unicode 'Ṧ' 'v\.S' 'Latin capital letter s with caron and dot above'
add-unicode 'ṧ' 'v\.s' 'Latin small letter s with caron and dot above'
add-unicode '│' 'vbar' 'Box drawings light vertical'
add-unicode 'Ǎ' 'v{A}' 'Latin capital letter a with caron'
add-unicode 'Č' 'v{C}' 'Latin capital letter c with caron'
add-unicode 'Ď' 'v{D}' 'Latin capital letter d with caron'
add-unicode 'Ě' 'v{E}' 'Latin capital letter e with caron'
add-unicode 'Ǧ' 'v{G}' 'Latin capital letter g with caron'
add-unicode 'Ȟ' 'v{H}' 'Latin capital letter h with caron'
add-unicode 'Ǐ' 'v{I}' 'Latin capital letter i with caron'
add-unicode 'Ǩ' 'v{K}' 'Latin capital letter k with caron'
add-unicode 'Ľ' 'v{L}' 'Latin capital letter l with caron'
add-unicode 'Ň' 'v{N}' 'Latin capital letter n with caron'
add-unicode 'Ǒ' 'v{O}' 'Latin capital letter o with caron'
add-unicode 'Ř' 'v{R}' 'Latin capital letter r with caron'
add-unicode 'Š' 'v{S}' 'Latin capital letter s with caron'
add-unicode 'Ť' 'v{T}' 'Latin capital letter t with caron'
add-unicode 'Ǔ' 'v{U}' 'Latin capital letter u with caron'
add-unicode 'Ž' 'v{Z}' 'Latin capital letter z with caron'
add-unicode 'ǎ' 'v{a}' 'Latin small letter a with caron'
add-unicode 'č' 'v{c}' 'Latin small letter c with caron'
add-unicode 'ď' 'v{d}' 'Latin small letter d with caron'
add-unicode 'ě' 'v{e}' 'Latin small letter e with caron'
add-unicode 'ǧ' 'v{g}' 'Latin small letter g with caron'
add-unicode 'ȟ' 'v{h}' 'Latin small letter h with caron'
add-unicode 'ǐ' 'v{i}' 'Latin small letter i with caron'
add-unicode 'ǰ' 'v{j}' 'Latin small letter j with caron'
add-unicode 'ǩ' 'v{k}' 'Latin small letter k with caron'
add-unicode 'ľ' 'v{l}' 'Latin small letter l with caron'
add-unicode 'ň' 'v{n}' 'Latin small letter n with caron'
add-unicode 'ǒ' 'v{o}' 'Latin small letter o with caron'
add-unicode 'ř' 'v{r}' 'Latin small letter r with caron'
add-unicode 'š' 'v{s}' 'Latin small letter s with caron'
add-unicode 'ť' 'v{t}' 'Latin small letter t with caron'
add-unicode 'ǔ' 'v{u}' 'Latin small letter u with caron'
add-unicode 'ž' 'v{z}' 'Latin small letter z with caron'
add-unicode 'Ṏ' '~\"O' 'Latin capital letter o with tilde and diaeresis'
add-unicode 'ṏ' '~\"o' 'Latin small letter o with tilde and diaeresis'
add-unicode 'Ṍ' '~\''O' 'Latin capital letter o with tilde and acute'
add-unicode 'Ṹ' '~\''U' 'Latin capital letter u with tilde and acute'
add-unicode 'ṍ' '~\''o' 'Latin small letter o with tilde and acute'
add-unicode 'ṹ' '~\''u' 'Latin small letter u with tilde and acute'
add-unicode 'Ȭ' '~\=O' 'Latin capital letter o with tilde and macron'
add-unicode 'ȭ' '~\=o' 'Latin small letter o with tilde and macron'
add-unicode 'Ã' '~{A}' 'Latin capital letter a with tilde'
add-unicode 'Ẽ' '~{E}' 'Latin capital letter e with tilde'
add-unicode 'Ĩ' '~{I}' 'Latin capital letter i with tilde'
add-unicode 'Ñ' '~{N}' 'Latin capital letter n with tilde'
add-unicode 'Õ' '~{O}' 'Latin capital letter o with tilde'
add-unicode 'Ũ' '~{U}' 'Latin capital letter u with tilde'
add-unicode 'Ṽ' '~{V}' 'Latin capital letter v with tilde'
add-unicode 'Ỹ' '~{Y}' 'Latin capital letter y with tilde'
add-unicode 'ã' '~{a}' 'Latin small letter a with tilde'
add-unicode 'ẽ' '~{e}' 'Latin small letter e with tilde'
add-unicode 'ĩ' '~{i}' 'Latin small letter i with tilde'
add-unicode 'ñ' '~{n}' 'Latin small letter n with tilde'
add-unicode 'õ' '~{o}' 'Latin small letter o with tilde'
add-unicode 'ũ' '~{u}' 'Latin small letter u with tilde'
add-unicode 'ṽ' '~{v}' 'Latin small letter v with tilde'
add-unicode 'ỹ' '~{y}' 'Latin small letter y with tilde'
add-unicode 'ᵜ' '^\ain' 'Modifier letter small ain'
add-unicode 'ᵡ' '^\chi' 'Modifier letter small chi'
add-unicode 'ᵑ' '^\eng' 'Modifier letter small eng'
add-unicode 'ᶴ' '^\esh' 'Modifier letter small esh'
add-unicode 'ᶞ' '^\eth' 'Modifier letter small eth'
add-unicode 'ᶾ' '^\ezh' 'Modifier letter small ezh'
add-unicode 'ᶲ' '^\phi' 'Modifier letter small phi'
add-unicode '℠' '^{SM}' 'Service mark'
add-unicode '™' '^{TM}' 'Trade mark sign'
add-unicode 'Ǿ' '''{\O}' 'Latin capital letter o with stroke and acute'
add-unicode 'ǿ' '''{\o}' 'Latin small letter o with stroke and acute'
add-unicode 'ī' '={\i}' 'Latin small letter i with macron'
add-unicode 'Ϭ' 'Shima' 'Coptic capital letter shima'
add-unicode '⊩' 'Vdash' 'Forces'
add-unicode 'ĵ' '^{\j}' 'Latin small letter j with circumflex'
add-unicode '┴' 'above' 'Box drawings light up and horizontal'
add-unicode 'ℵ' 'aleph' 'Alef symbol'
add-unicode '∐' 'amalg' 'N-ary coproduct'
add-unicode '∠' 'angle' 'Angle'
add-unicode '∳' 'aoint' 'Anticlockwise contour integral'
add-unicode '≍' 'asymp' 'Equivalent to'
add-unicode '〖' 'begin' 'Left white lenticular bracket'
add-unicode '┬' 'below' 'Box drawings light down and horizontal'
add-unicode '⋯' 'cdots' 'Midline horizontal ellipsis'
add-unicode '┤' 'close' 'Box drawings light vertical and left'
add-unicode '∲' 'coint' 'Clockwise contour integral'
add-unicode '₡' 'colon' 'Colon sign'
add-unicode '⊣' 'dashv' 'Left tack'
add-unicode '⃛' 'dddot  ' 'Combining three dots above'
add-unicode '⋱' 'ddots' 'Down right diagonal ellipsis'
add-unicode '≐' 'doteq' 'Approaches the limit'
add-unicode '≡' 'equiv' 'Identical to'
add-unicode '⅟' 'frac1' 'Fraction numerator one'
add-unicode '⌢' 'frown' 'Frown'
add-unicode 'ℷ' 'gimel' 'Gimel symbol'
add-unicode '≩' 'gneqq' 'Greater-than but not equal to'
add-unicode '⋧' 'gnsim' 'Greater-than but not equivalent to'
add-unicode '∭' 'iiint' 'Triple integral'
add-unicode 'ı' 'imath' 'Latin small letter dotless i'
add-unicode '∞' 'infty' 'Infinity'
add-unicode 'ȷ' 'jmath' 'Latin small letter dotless j'
add-unicode '⌈' 'lceil' 'Left ceiling'
add-unicode '《' 'ldata' 'Left double angle bracket'
add-unicode '…' 'ldots' 'Horizontal ellipsis'
add-unicode '≨' 'lneqq' 'Less-than but not equal to'
add-unicode '⋦' 'lnsim' 'Less-than but not equivalent to'
add-unicode '₼' 'manat' 'Manat sign'
add-unicode 'µ' 'micro' 'Micro sign'
add-unicode '−' 'minus' 'Minus sign'
add-unicode '∇' 'nabla' 'Nabla'
add-unicode '₦' 'naira' 'Naira sign'
add-unicode '≇' 'ncong' 'Neither approximately nor actually equal to'
add-unicode '≱' 'ngeqq' 'Neither greater-than nor equal to'
add-unicode '≰' 'nleqq' 'Neither less-than nor equal to'
add-unicode '≮' 'nless' 'Not less-than'
add-unicode '∉' 'notin' 'Not an element of'
add-unicode '⊀' 'nprec' 'Does not precede'
add-unicode '⊁' 'nsucc' 'Does not succeed'
add-unicode '∯' 'oiint' 'Surface integral'
add-unicode '⊕' 'oplus' 'Circled plus'
add-unicode '℥' 'ounce' 'Ounce sign'
add-unicode '£' 'pound' 'Pound sign'
add-unicode '≼' 'prcue' 'Precedes or equal to'
add-unicode '′' 'prime' 'Prime'
add-unicode '∶' 'ratio' 'Ratio'
add-unicode '⌉' 'rceil' 'Right ceiling'
add-unicode '》' 'rdata' 'Right double angle bracket'
add-unicode '▢' 'rrect' 'White square with rounded corners'
add-unicode '₽' 'ruble' 'Ruble sign'
add-unicode '₨' 'rupee' 'Rupee sign'
add-unicode '♯' 'sharp' 'Music sharp sign'
add-unicode 'ϭ' 'shima' 'Coptic small letter shima'
add-unicode '≃' 'simeq' 'Asymptotically equal to'
add-unicode '⬍' 'smash' 'Up down black arrow'
add-unicode '⌣' 'smile' 'Smile'
add-unicode '⊓' 'sqcap' 'Square cap'
add-unicode '⊔' 'sqcup' 'Square cup'
add-unicode '₸' 'tenge' 'Tenge sign'
add-unicode '×' 'times' 'Multiplication sign'
add-unicode '⊎' 'uplus' 'Multiset union'
add-unicode 'ĭ' 'u{\i}' 'Latin small letter i with breve'
add-unicode '⊨' 'vDash' 'True'
add-unicode '⊢' 'vdash' 'Right tack'
add-unicode '⋮' 'vdots' 'Vertical ellipsis'
add-unicode 'ǐ' 'v{\i}' 'Latin small letter i with caron'
add-unicode 'ǰ' 'v{\j}' 'Latin small letter j with caron'
add-unicode '∧' 'wedge' 'Logical and'
add-unicode 'ĩ' '~{\i}' 'Latin small letter i with tilde'
add-unicode 'ᵝ' '^\beta' 'Modifier letter small beta'
add-unicode 'ꭜ' '^\heng' 'Modifier letter small heng'
add-unicode 'ᶥ' '^\iota' 'Modifier letter small iota'
add-unicode '𐞞' '^\lezh' ''
add-unicode '℡' '^{TEL}' 'Telephone sign'
add-unicode 'Ḯ' '"\''{I}' 'Latin capital letter i with diaeresis and acute'
add-unicode 'Ǘ' '"\''{U}' 'Latin capital letter u with diaeresis and acute'
add-unicode 'ḯ' '"\''{i}' 'Latin small letter i with diaeresis and acute'
add-unicode 'ǘ' '"\''{u}' 'Latin small letter u with diaeresis and acute'
add-unicode 'Ǟ' '"\={A}' 'Latin capital letter a with diaeresis and macron'
add-unicode 'Ȫ' '"\={O}' 'Latin capital letter o with diaeresis and macron'
add-unicode 'Ǖ' '"\={U}' 'Latin capital letter u with diaeresis and macron'
add-unicode 'ǟ' '"\={a}' 'Latin small letter a with diaeresis and macron'
add-unicode 'ȫ' '"\={o}' 'Latin small letter o with diaeresis and macron'
add-unicode 'ǖ' '"\={u}' 'Latin small letter u with diaeresis and macron'
add-unicode 'Ǜ' '"\`{U}' 'Latin capital letter u with diaeresis and grave'
add-unicode 'ǜ' '"\`{u}' 'Latin small letter u with diaeresis and grave'
add-unicode 'Ǚ' '"\v{U}' 'Latin capital letter u with diaeresis and caron'
add-unicode 'ǚ' '"\v{u}' 'Latin small letter u with diaeresis and caron'
add-unicode 'Ṥ' '''\.{S}' 'Latin capital letter s with acute and dot above'
add-unicode 'ṥ' '''\.{s}' 'Latin small letter s with acute and dot above'
add-unicode 'Ǽ' '''{\AE}' 'Latin capital letter ae with acute'
add-unicode 'ǽ' '''{\ae}' 'Latin small letter ae with acute'
add-unicode 'Ǡ' '.\={A}' 'Latin capital letter a with dot above and macron'
add-unicode 'Ȱ' '.\={O}' 'Latin capital letter o with dot above and macron'
add-unicode 'ǡ' '.\={a}' 'Latin small letter a with dot above and macron'
add-unicode 'ȱ' '.\={o}' 'Latin small letter o with dot above and macron'
add-unicode 'Ṻ' '=\"{U}' 'Latin capital letter u with macron and diaeresis'
add-unicode 'ṻ' '=\"{u}' 'Latin small letter u with macron and diaeresis'
add-unicode 'Ḗ' '=\''{E}' 'Latin capital letter e with macron and acute'
add-unicode 'Ṓ' '=\''{O}' 'Latin capital letter o with macron and acute'
add-unicode 'ḗ' '=\''{e}' 'Latin small letter e with macron and acute'
add-unicode 'ṓ' '=\''{o}' 'Latin small letter o with macron and acute'
add-unicode 'Ḕ' '=\`{E}' 'Latin capital letter e with macron and grave'
add-unicode 'Ṑ' '=\`{O}' 'Latin capital letter o with macron and grave'
add-unicode 'ḕ' '=\`{e}' 'Latin small letter e with macron and grave'
add-unicode 'ṑ' '=\`{o}' 'Latin small letter o with macron and grave'
add-unicode 'Ǣ' '={\AE}' 'Latin capital letter ae with macron'
add-unicode 'ǣ' '={\ae}' 'Latin small letter ae with macron'
add-unicode '𝟙' 'Bbb{1}' 'Mathematical double-struck digit one'
add-unicode '𝟚' 'Bbb{2}' 'Mathematical double-struck digit two'
add-unicode '𝔸' 'Bbb{A}' 'Mathematical double-struck capital a'
add-unicode '𝔹' 'Bbb{B}' 'Mathematical double-struck capital b'
add-unicode 'ℂ' 'Bbb{C}' 'Double-struck capital c'
add-unicode '𝔻' 'Bbb{D}' 'Mathematical double-struck capital d'
add-unicode '𝔼' 'Bbb{E}' 'Mathematical double-struck capital e'
add-unicode '𝔽' 'Bbb{F}' 'Mathematical double-struck capital f'
add-unicode '𝔾' 'Bbb{G}' 'Mathematical double-struck capital g'
add-unicode 'ℍ' 'Bbb{H}' 'Double-struck capital h'
add-unicode '𝕀' 'Bbb{I}' 'Mathematical double-struck capital i'
add-unicode '𝕁' 'Bbb{J}' 'Mathematical double-struck capital j'
add-unicode '𝕂' 'Bbb{K}' 'Mathematical double-struck capital k'
add-unicode '𝕃' 'Bbb{L}' 'Mathematical double-struck capital l'
add-unicode '𝕄' 'Bbb{M}' 'Mathematical double-struck capital m'
add-unicode 'ℕ' 'Bbb{N}' 'Double-struck capital n'
add-unicode '𝕆' 'Bbb{O}' 'Mathematical double-struck capital o'
add-unicode 'ℙ' 'Bbb{P}' 'Double-struck capital p'
add-unicode 'ℚ' 'Bbb{Q}' 'Double-struck capital q'
add-unicode 'ℝ' 'Bbb{R}' 'Double-struck capital r'
add-unicode '𝕊' 'Bbb{S}' 'Mathematical double-struck capital s'
add-unicode '𝕋' 'Bbb{T}' 'Mathematical double-struck capital t'
add-unicode '𝕌' 'Bbb{U}' 'Mathematical double-struck capital u'
add-unicode '𝕍' 'Bbb{V}' 'Mathematical double-struck capital v'
add-unicode '𝕎' 'Bbb{W}' 'Mathematical double-struck capital w'
add-unicode '𝕏' 'Bbb{X}' 'Mathematical double-struck capital x'
add-unicode '𝕐' 'Bbb{Y}' 'Mathematical double-struck capital y'
add-unicode 'ℤ' 'Bbb{Z}' 'Double-struck capital z'
add-unicode '≎' 'Bumpeq' 'Geometrically equivalent to'
add-unicode '☹' 'Frowny' 'White frowning face'
add-unicode 'Ϫ' 'Gangia' 'Coptic capital letter gangia'
add-unicode '✉' 'Letter' 'Envelope'
add-unicode '☺' 'Smiley' 'White smiling face'
add-unicode '⋐' 'Subset' 'Double subset'
add-unicode '⋑' 'Supset' 'Double superset'
add-unicode '⊪' 'Vvdash' 'Triple vertical bar right turnstile'
add-unicode 'Ấ' '^\''{A}' 'Latin capital letter a with circumflex and acute'
add-unicode 'Ế' '^\''{E}' 'Latin capital letter e with circumflex and acute'
add-unicode 'Ố' '^\''{O}' 'Latin capital letter o with circumflex and acute'
add-unicode 'ấ' '^\''{a}' 'Latin small letter a with circumflex and acute'
add-unicode 'ế' '^\''{e}' 'Latin small letter e with circumflex and acute'
add-unicode 'ố' '^\''{o}' 'Latin small letter o with circumflex and acute'
add-unicode 'Ầ' '^\`{A}' 'Latin capital letter a with circumflex and grave'
add-unicode 'Ề' '^\`{E}' 'Latin capital letter e with circumflex and grave'
add-unicode 'Ồ' '^\`{O}' 'Latin capital letter o with circumflex and grave'
add-unicode 'ầ' '^\`{a}' 'Latin small letter a with circumflex and grave'
add-unicode 'ề' '^\`{e}' 'Latin small letter e with circumflex and grave'
add-unicode 'ồ' '^\`{o}' 'Latin small letter o with circumflex and grave'
add-unicode 'Ậ' '^\d{A}' 'Latin capital letter a with circumflex and dot below'
add-unicode 'Ệ' '^\d{E}' 'Latin capital letter e with circumflex and dot below'
add-unicode 'Ộ' '^\d{O}' 'Latin capital letter o with circumflex and dot below'
add-unicode 'ậ' '^\d{a}' 'Latin small letter a with circumflex and dot below'
add-unicode 'ệ' '^\d{e}' 'Latin small letter e with circumflex and dot below'
add-unicode 'ộ' '^\d{o}' 'Latin small letter o with circumflex and dot below'
add-unicode 'Ẫ' '^\~{A}' 'Latin capital letter a with circumflex and tilde'
add-unicode 'Ễ' '^\~{E}' 'Latin capital letter e with circumflex and tilde'
add-unicode 'Ỗ' '^\~{O}' 'Latin capital letter o with circumflex and tilde'
add-unicode 'ẫ' '^\~{a}' 'Latin small letter a with circumflex and tilde'
add-unicode 'ễ' '^\~{e}' 'Latin small letter e with circumflex and tilde'
add-unicode 'ỗ' '^\~{o}' 'Latin small letter o with circumflex and tilde'
add-unicode '≈' 'approx' 'Almost equal to'
add-unicode '⬆' 'asmash' 'Upwards black arrow'
add-unicode '⋂' 'bigcap' 'N-ary intersection'
add-unicode '⋃' 'bigcup' 'N-ary union'
add-unicode '⋁' 'bigvee' 'N-ary logical or'
add-unicode '⋈' 'bowtie' 'Bowtie'
add-unicode '•' 'bullet' 'Bullet'
add-unicode '≏' 'bumpeq' 'Difference between'
add-unicode 'Ḉ' 'c\''{C}' 'Latin capital letter c with cedilla and acute'
add-unicode 'ḉ' 'c\''{c}' 'Latin small letter c with cedilla and acute'
add-unicode 'Ḝ' 'c\u{E}' 'Latin capital letter e with cedilla and breve'
add-unicode 'ḝ' 'c\u{e}' 'Latin small letter e with cedilla and breve'
add-unicode '≗' 'circeq' 'Ring equal to'
add-unicode '∐' 'coprod' 'N-ary coproduct'
add-unicode 'Ṩ' 'd\.{S}' 'Latin capital letter s with dot below and dot above'
add-unicode 'ṩ' 'd\.{s}' 'Latin small letter s with dot below and dot above'
add-unicode 'Ḹ' 'd\={L}' 'Latin capital letter l with dot below and macron'
add-unicode 'Ṝ' 'd\={R}' 'Latin capital letter r with dot below and macron'
add-unicode 'ḹ' 'd\={l}' 'Latin small letter l with dot below and macron'
add-unicode 'ṝ' 'd\={r}' 'Latin small letter r with dot below and macron'
add-unicode '†' 'dagger' 'Dagger'
add-unicode 'ℸ' 'daleth' 'Dalet symbol'
add-unicode '⃜' 'ddddot' 'Combining four dots above'
add-unicode '°' 'degree' 'Degree sign'
add-unicode '⬇' 'dsmash' 'Downwards black arrow'
add-unicode '≖' 'eqcirc' 'Ring in equal to'
add-unicode '∃' 'exists' 'There exists'
add-unicode '♀' 'female' 'Female sign'
add-unicode '∀' 'forall' 'For all'
add-unicode '½' 'frac12' 'Vulgar fraction one half'
add-unicode '⅓' 'frac13' 'Vulgar fraction one third'
add-unicode '¼' 'frac14' 'Vulgar fraction one quarter'
add-unicode '⅕' 'frac15' 'Vulgar fraction one fifth'
add-unicode '⅙' 'frac16' 'Vulgar fraction one sixth'
add-unicode '⅛' 'frac18' 'Vulgar fraction one eighth'
add-unicode '⅔' 'frac23' 'Vulgar fraction two thirds'
add-unicode '⅖' 'frac25' 'Vulgar fraction two fifths'
add-unicode '¾' 'frac34' 'Vulgar fraction three quarters'
add-unicode '⅗' 'frac35' 'Vulgar fraction three fifths'
add-unicode '⅜' 'frac38' 'Vulgar fraction three eighths'
add-unicode '⅘' 'frac45' 'Vulgar fraction four fifths'
add-unicode '⅚' 'frac56' 'Vulgar fraction five sixths'
add-unicode '⅝' 'frac58' 'Vulgar fraction five eighths'
add-unicode '⅞' 'frac78' 'Vulgar fraction seven eighths'
add-unicode 'ϫ' 'gangia' 'Coptic small letter gangia'
add-unicode '⋗' 'gtrdot' 'Greater-than with dot'
add-unicode '≳' 'gtrsim' 'Greater-than or equivalent to'
add-unicode '⬌' 'hsmash' 'Left right black arrow'
add-unicode '⨌' 'iiiint' 'Quadruple integral operator'
add-unicode 'Ǭ' 'k\={O}' 'Latin capital letter o with ogonek and macron'
add-unicode 'ǭ' 'k\={o}' 'Latin small letter o with ogonek and macron'
add-unicode 'K' 'kelvin' 'Kelvin sign'
add-unicode '⟨' 'langle' 'Mathematical left angle bracket'
add-unicode '⌊' 'lfloor' 'Left floor'
add-unicode '⋉' 'ltimes' 'Left normal factor semidirect product'
add-unicode '↦' 'mapsto' 'Rightwards arrow from bar'
add-unicode '⊧' 'models' 'Models'
add-unicode '⊯' 'nVDash' 'Negated double vertical bar double right turnstile'
add-unicode '⊮' 'nVdash' 'Does not force'
add-unicode '≢' 'nequiv' 'Not identical to'
add-unicode '≄' 'nsimeq' 'Not asymptotically equal to'
add-unicode '№' 'numero' 'Numero sign'
add-unicode '⊭' 'nvDash' 'Not true'
add-unicode '⊬' 'nvdash' 'Does not prove'
add-unicode '∰' 'oiiint' 'Volume integral'
add-unicode '⊖' 'ominus' 'Circled minus'
add-unicode '⊘' 'oslash' 'Circled division slash'
add-unicode '⊗' 'otimes' 'Circled times'
add-unicode '‰' 'permil' 'Per mille sign'
add-unicode '₧' 'peseta' 'Peseta sign'
add-unicode '£' 'pounds' 'Pound sign'
add-unicode '″' 'pprime' 'Double prime'
add-unicode '≼' 'preceq' 'Precedes or equal to'
add-unicode '∝' 'propto' 'Proportional to'
add-unicode '⟩' 'rangle' 'Mathematical right angle bracket'
add-unicode '⋰' 'rddots' 'Up right diagonal ellipsis'
add-unicode '⌋' 'rfloor' 'Right floor'
add-unicode '⋊' 'rtimes' 'Right normal factor semidirect product'
add-unicode '□' 'square' 'White square'
add-unicode '⊂' 'subset' 'Subset of'
add-unicode '≽' 'succeq' 'Succeeds or equal to'
add-unicode '⊃' 'supset' 'Superset of'
add-unicode 'µ' 'textmu' 'Micro sign'
add-unicode '₮' 'tugrik' 'Tugrik sign'
add-unicode 'Ắ' 'u\''{A}' 'Latin capital letter a with breve and acute'
add-unicode 'ắ' 'u\''{a}' 'Latin small letter a with breve and acute'
add-unicode 'Ằ' 'u\`{A}' 'Latin capital letter a with breve and grave'
add-unicode 'ằ' 'u\`{a}' 'Latin small letter a with breve and grave'
add-unicode 'Ặ' 'u\d{A}' 'Latin capital letter a with breve and dot below'
add-unicode 'ặ' 'u\d{a}' 'Latin small letter a with breve and dot below'
add-unicode 'Ẵ' 'u\~{A}' 'Latin capital letter a with breve and tilde'
add-unicode 'ẵ' 'u\~{a}' 'Latin small letter a with breve and tilde'
add-unicode 'Ṧ' 'v\.{S}' 'Latin capital letter s with caron and dot above'
add-unicode 'ṧ' 'v\.{s}' 'Latin small letter s with caron and dot above'
add-unicode '⊻' 'veebar' 'Xor'
add-unicode 'Ṏ' '~\"{O}' 'Latin capital letter o with tilde and diaeresis'
add-unicode 'ṏ' '~\"{o}' 'Latin small letter o with tilde and diaeresis'
add-unicode 'Ṍ' '~\''{O}' 'Latin capital letter o with tilde and acute'
add-unicode 'Ṹ' '~\''{U}' 'Latin capital letter u with tilde and acute'
add-unicode 'ṍ' '~\''{o}' 'Latin small letter o with tilde and acute'
add-unicode 'ṹ' '~\''{u}' 'Latin small letter u with tilde and acute'
add-unicode 'Ȭ' '~\={O}' 'Latin capital letter o with tilde and macron'
add-unicode 'ȭ' '~\={o}' 'Latin small letter o with tilde and macron'
add-unicode 'ᵅ' '^\alpha' 'Modifier letter small alpha'
add-unicode 'ᵟ' '^\delta' 'Modifier letter small delta'
add-unicode 'ˠ' '^\gamma' 'Modifier letter small gamma'
add-unicode 'ᵊ' '^\schwa' 'Modifier letter small schwa'
add-unicode 'ᶿ' '^\theta' 'Modifier letter small theta'
add-unicode 'ᶶ' '^\u_bar' 'Modifier letter small u bar'
add-unicode '×' '\times' 'Multiplication sign'
add-unicode '◇' 'Diamond' 'White diamond'
add-unicode '⇑' 'Uparrow' 'Upwards double arrow'
add-unicode '؋' 'afghani' 'Afghani sign'
add-unicode '₳' 'austral' 'Austral sign'
add-unicode '∽' 'backsim' 'Reversed tilde'
add-unicode '∵' 'because' 'Because'
add-unicode '≬' 'between' 'Between'
add-unicode '◯' 'bigcirc' 'Large circle'
add-unicode '⨀' 'bigodot' 'N-ary circled dot operator'
add-unicode '★' 'bigstar' 'Black star'
add-unicode '₿' 'bitcoin' 'Bitcoin sign'
add-unicode '⊞' 'boxplus' 'Squared plus'
add-unicode '☡' 'caution' 'Caution sign'
add-unicode '℃' 'celsius' 'Degree celsius'
add-unicode '≔' 'coloneq' 'Colon equals'
add-unicode '‡' 'ddagger' 'Double dagger'
add-unicode '⋄' 'diamond' 'Diamond operator'
add-unicode '∔' 'dotplus' 'Dot plus'
add-unicode '₯' 'drachma' 'Drachma sign'
add-unicode '█' 'eqarray' 'Full block'
add-unicode '≕' 'eqcolon' 'Equals colon'
add-unicode '≷' 'gtrless' 'Greater-than or less-than'
add-unicode '₲' 'guarani' 'Guarani sign'
add-unicode '₴' 'hryvnia' 'Hryvnia sign'
add-unicode '↝' 'leadsto' 'Rightwards wave arrow'
add-unicode '⋖' 'lessdot' 'Less-than with dot'
add-unicode '≶' 'lessgtr' 'Less-than or greater-than'
add-unicode '≲' 'lesssim' 'Less-than or equivalent to'
add-unicode '✧' 'lozenge' 'White four pointed star'
add-unicode '✠' 'maltese' 'Maltese cross'
add-unicode '≉' 'napprox' 'Not almost equal to'
add-unicode '♮' 'natural' 'Music natural sign'
add-unicode '↗' 'nearrow' 'North east arrow'
add-unicode '∄' 'nexists' 'There does not exist'
add-unicode '𐆎' 'nomisma' 'Nomisma sign'
add-unicode '⋠' 'npreceq' 'Does not precede or equal'
add-unicode '⊄' 'nsubset' 'Not a subset of'
add-unicode '⋡' 'nsucceq' 'Does not succeed or equal'
add-unicode '⊅' 'nsupset' 'Not a superset of'
add-unicode '↖' 'nwarrow' 'North west arrow'
add-unicode '∂' 'partial' 'Partial differential'
add-unicode '⟡' 'phantom' 'White concave-sided diamond'
add-unicode '¶' 'pilcrow' 'Pilcrow sign'
add-unicode '‴' 'ppprime' 'Triple prime'
add-unicode '≾' 'precsim' 'Precedes or equivalent to'
add-unicode '↘' 'searrow' 'South east arrow'
add-unicode '§' 'section' 'Section sign'
add-unicode '∛' 'sqrt[3]' 'Cube root'
add-unicode '∜' 'sqrt[4]' 'Fourth root'
add-unicode '≿' 'succsim' 'Succeeds or equivalent to'
add-unicode '↙' 'swarrow' 'South west arrow'
add-unicode '₩' 'textwon' 'Won sign'
add-unicode '↑' 'uparrow' 'Upwards arrow'
add-unicode '⚠' 'warning' 'Warning sign'
add-unicode 'ʱ' '^\h_hook' 'Modifier letter small h with hook'
add-unicode 'ᵋ' '^\open_e' 'Modifier letter small open e'
add-unicode 'ᵓ' '^\open_o' 'Modifier letter small open o'
add-unicode 'Å' 'angstrom' 'Angstrom sign'
add-unicode '≊' 'approxeq' 'Almost equal or equal to'
add-unicode '≌' 'backcong' 'All equal to'
add-unicode '⊼' 'barwedge' 'Nand'
add-unicode '⨁' 'bigoplus' 'N-ary circled plus operator'
add-unicode '⨆' 'bigsqcup' 'N-ary square union operator'
add-unicode '⨄' 'biguplus' 'N-ary union operator with plus'
add-unicode '⋀' 'bigwedge' 'N-ary logical and'
add-unicode '⊟' 'boxminus' 'Squared minus'
add-unicode '⊠' 'boxtimes' 'Squared times'
add-unicode '®' 'circledR' 'Registered sign'
add-unicode 'Ⓢ' 'circledS' 'Circled latin capital letter s'
add-unicode '♣' 'clubsuit' 'Black club suit'
add-unicode '₢' 'cruzeiro' 'Cruzeiro sign'
add-unicode '⋎' 'curlyvee' 'Curly logical or'
add-unicode '¤' 'currency' 'Currency sign'
add-unicode '⌀' 'diameter' 'Diameter sign'
add-unicode '÷' 'division' 'Division sign'
add-unicode '≑' 'doteqdot' 'Geometrically equal to'
add-unicode '∅' 'emptyset' 'Empty set'
add-unicode '≥' 'geqslant' 'Greater-than or equal to'
add-unicode '⋧' 'gnapprox' 'Greater-than but not equivalent to'
add-unicode '⬄' 'hphantom' 'Left right white arrow'
add-unicode '⊺' 'intercal' 'Intercalate'
add-unicode '≤' 'leqslant' 'Less-than or equal to'
add-unicode '⌞' 'llcorner' 'Bottom left corner'
add-unicode '⋦' 'lnapprox' 'Less-than but not equivalent to'
add-unicode '⌟' 'lrcorner' 'Bottom right corner'
add-unicode '⊸' 'multimap' 'Multimap'
add-unicode '∥' 'parallel' 'Parallel to'
add-unicode '⁗' 'pppprime' 'Quadruple prime'
add-unicode '⋨' 'precnsim' 'Precedes but not equivalent to'
add-unicode '∖' 'setminus' 'Set minus'
add-unicode '∣' 'shortmid' 'Divides'
add-unicode '₷' 'spesmilo' 'Spesmilo sign'
add-unicode '⊏' 'sqsubset' 'Square image of'
add-unicode '⊐' 'sqsupset' 'Square original of'
add-unicode '⊆' 'subseteq' 'Subset of or equal to'
add-unicode '⋩' 'succnsim' 'Succeeds but not equivalent to'
add-unicode '⊇' 'supseteq' 'Superset of or equal to'
add-unicode '฿' 'textbaht' 'Thai currency symbol baht'
add-unicode '✝' 'textdied' 'Latin cross'
add-unicode '₤' 'textlira' 'Lira sign'
add-unicode '₱' 'textpeso' 'Peso sign'
add-unicode '∼' 'thicksim' 'Tilde operator'
add-unicode '▵' 'triangle' 'White up-pointing small triangle'
add-unicode '⌜' 'ulcorner' 'Top left corner'
add-unicode '▁' 'underbar' 'Lower one eighth block'
add-unicode '⌝' 'urcorner' 'Top right corner'
add-unicode '′' 'varprime' 'Prime'
add-unicode '⇳' 'vphantom' 'Up down white arrow'
add-unicode 'ᶷ' '^\upsilon' 'Modifier letter small upsilon'
add-unicode '⇓' 'Downarrow' 'Downwards double arrow'
add-unicode '⇐' 'Leftarrow' 'Leftwards double arrow'
add-unicode '‵' 'backprime' 'Reversed prime'
add-unicode '⋍' 'backsimeq' 'Reversed tilde equals'
add-unicode '⨂' 'bigotimes' 'N-ary circled times operator'
add-unicode '☣' 'biohazard' 'Biohazard sign'
add-unicode '·' 'centerdot' 'Middle dot'
add-unicode '✓' 'checkmark' 'Check mark'
add-unicode '©' 'copyright' 'Copyright sign'
add-unicode '⊡' 'dotsquare' 'Squared dot operator'
add-unicode '↓' 'downarrow' 'Downwards arrow'
add-unicode '℻' 'facsimile' 'Facsimile sign'
add-unicode '≳' 'gtrapprox' 'Greater-than or equivalent to'
add-unicode '⋛' 'gtreqless' 'Greater-than equal to or less-than'
add-unicode '≩' 'gvertneqq' 'Greater-than but not equal to'
add-unicode '♥' 'heartsuit' 'Black heart suit'
add-unicode '←' 'leftarrow' 'Leftwards arrow'
add-unicode '⋚' 'lesseqgtr' 'Less-than equal to or greater-than'
add-unicode '〚' 'llbracket' 'Left white square bracket'
add-unicode '≨' 'lvertneqq' 'Less-than but not equal to'
add-unicode '≱' 'ngeqslant' 'Neither greater-than nor equal to'
add-unicode '≰' 'nleqslant' 'Neither less-than nor equal to'
add-unicode '∦' 'nparallel' 'Not parallel to'
add-unicode '∤' 'nshortmid' 'Does not divide'
add-unicode '⊈' 'nsubseteq' 'Neither a subset of nor equal to'
add-unicode '⊉' 'nsupseteq' 'Neither a superset of nor equal to'
add-unicode '🛑' 'octagonal' 'Octagonal sign'
add-unicode '⏞' 'overbrace' 'Top curly bracket'
add-unicode '⏜' 'overparen' 'Top parenthesis'
add-unicode '¶' 'paragraph' 'Pilcrow sign'
add-unicode '⋔' 'pitchfork' 'Pitchfork'
add-unicode '〛' 'rrbracket' 'Right white square bracket'
add-unicode '♠' 'spadesuit' 'Black spade suit'
add-unicode '⊆' 'subseteqq' 'Subset of or equal to'
add-unicode '⊊' 'subsetneq' 'Subset of with not equal to'
add-unicode '⊇' 'supseteqq' 'Superset of or equal to'
add-unicode '⊋' 'supsetneq' 'Superset of with not equal to'
add-unicode '℡' 'telephone' 'Telephone sign'
add-unicode '₦' 'textnaira' 'Naira sign'
add-unicode '∴' 'therefore' 'Therefore'
add-unicode '≜' 'triangleq' 'Delta equal to'
add-unicode '∝' 'varpropto' 'Proportional to'
add-unicode 'ᴯ' '^\Barred_B' 'Modifier letter capital barred b'
add-unicode 'ᶱ' '^\barred_o' 'Modifier letter small barred o'
add-unicode 'ᶢ' '^\script_g' 'Modifier letter small script g'
add-unicode 'ᵄ' '^\turned_a' 'Modifier letter small turned a'
add-unicode 'ᶣ' '^\turned_h' 'Modifier letter small turned h'
add-unicode 'ᵎ' '^\turned_i' 'Modifier letter small turned i'
add-unicode 'ᵚ' '^\turned_m' 'Modifier letter small turned m'
add-unicode 'ʴ' '^\turned_r' 'Modifier letter small turned r'
add-unicode 'ᶺ' 'turned_v' 'Modifier letter small turned v'
add-unicode 'ꭩ' '^\turned_w' 'Modifier letter small turned w'
add-unicode '𐞠' '^\turned_y' ''
add-unicode '⇚' 'Lleftarrow' 'Leftwards triple arrow'
add-unicode '⇒' 'Rightarrow' 'Rightwards double arrow'
add-unicode '⊛' 'circledast' 'Circled asterisk operator'
add-unicode '∁' 'complement' 'Complement'
add-unicode '⋏' 'curlywedge' 'Curly logical and'
add-unicode '⋝' 'eqslantgtr' 'Equal to or greater-than'
add-unicode '⋛' 'gtreqqless' 'Greater-than equal to or less-than'
add-unicode '≲' 'lessapprox' 'Less-than or equivalent to'
add-unicode '⋚' 'lesseqqgtr' 'Less-than equal to or greater-than'
add-unicode '⟼' 'longmapsto' 'Long rightwards arrow from bar'
add-unicode 'ℐ' 'mathscr{I}' 'Script capital i'
add-unicode '⇍' 'nLeftarrow' 'Leftwards double arrow with stroke'
add-unicode '↚' 'nleftarrow' 'Leftwards arrow with stroke'
add-unicode '⊈' 'nsubseteqq' 'Neither a subset of nor equal to'
add-unicode '⊉' 'nsupseteqq' 'Neither a superset of nor equal to'
add-unicode '≾' 'precapprox' 'Precedes or equivalent to'
add-unicode '🛇' 'prohibited' 'Prohibited sign'
add-unicode '®' 'registered' 'Registered sign'
add-unicode '→' 'rightarrow' 'Rightwards arrow'
add-unicode '∐' 'smallamalg' 'N-ary coproduct'
add-unicode '⌣' 'smallsmile' 'Smile'
add-unicode '⊑' 'sqsubseteq' 'Square image of or equal to'
add-unicode '⊒' 'sqsupseteq' 'Square original of or equal to'
add-unicode '⊊' 'subsetneqq' 'Subset of with not equal to'
add-unicode '≿' 'succapprox' 'Succeeds or equivalent to'
add-unicode '⊋' 'supsetneqq' 'Superset of with not equal to'
add-unicode '⁅' 'textlquill' 'Left square bracket with quill'
add-unicode '№' 'textnumero' 'Numero sign'
add-unicode '℞' 'textrecipe' 'Prescription take'
add-unicode '⁆' 'textrquill' 'Right square bracket with quill'
add-unicode '⏟' 'underbrace' 'Bottom curly bracket'
add-unicode '⏝' 'underparen' 'Bottom parenthesis'
add-unicode '⇈' 'upuparrows' 'Upwards paired arrows'
add-unicode '𐞄' '^\capital_b' ''
add-unicode '𐞒' '^\capital_g' ''
add-unicode '𐞖' '^\capital_h' ''
add-unicode 'ᶦ' '^\capital_i' 'Modifier letter small capital i'
add-unicode 'ᶫ' '^\capital_l' 'Modifier letter small capital l'
add-unicode 'ᶰ' '^\capital_n' 'Modifier letter small capital n'
add-unicode '𐞪' '^\capital_r' ''
add-unicode 'ᶸ' '^\capital_u' 'Modifier letter small capital u'
add-unicode '𐞲' '^\capital_y' ''
add-unicode 'ᵠ' '^\greek_phi' 'Modifier letter small greek phi'
add-unicode '𐞑' '^\rams_horn' ''
add-unicode 'ᵆ' '^\turned_ae' 'Modifier letter small turned ae'
add-unicode '⇛' 'Rrightarrow' 'Rightwards triple arrow'
add-unicode '⇕' 'Updownarrow' 'Up down double arrow'
add-unicode '∍' 'backepsilon' 'Small contains as member'
add-unicode '☻' 'blacksmiley' 'Black smiling face'
add-unicode '▪' 'blacksquare' 'Black small square'
add-unicode '⊚' 'circledcirc' 'Circled ring operator'
add-unicode '⊝' 'circleddash' 'Circled dash'
add-unicode '⋞' 'curlyeqprec' 'Equal to or precedes'
add-unicode '⋟' 'curlyeqsucc' 'Equal to or succeeds'
add-unicode '≼' 'curlypreceq' 'Precedes or equal to'
add-unicode '♢' 'diamondsuit' 'White diamond suit'
add-unicode '⋜' 'eqslantless' 'Equal to or less-than'
add-unicode '⇏' 'nRightarrow' 'Rightwards double arrow with stroke'
add-unicode '↛' 'nrightarrow' 'Rightwards arrow with stroke'
add-unicode 'ª' 'ordfeminine' 'Feminine ordinal indicator'
add-unicode '㉐' 'partnership' 'Partnership sign'
add-unicode '⋨' 'precnapprox' 'Precedes but not equivalent to'
add-unicode '☢' 'radioactive' 'Radioactive sign'
add-unicode '≽' 'succcurlyeq' 'Succeeds or equal to'
add-unicode '⋩' 'succnapprox' 'Succeeds but not equivalent to'
add-unicode '≈' 'thickapprox' 'Almost equal to'
add-unicode '⯑' 'uncertainty' 'Uncertainty sign'
add-unicode '↕' 'updownarrow' 'Up down arrow'
add-unicode 'ᴲ' '^\Reversed_E' 'Modifier letter capital reversed e'
add-unicode 'ᴻ' '^\Reversed_N' 'Modifier letter capital reversed n'
add-unicode '𐞀' '^\capital_aa' ''
add-unicode '𐞣' '^\capital_oe' ''
add-unicode '𐞇' '^\dz_digraph' ''
add-unicode '𐞙' '^\ls_digraph' ''
add-unicode '𐞚' '^\lz_digraph' ''
add-unicode '𐞎' '^\reversed_e' ''
add-unicode 'ᵙ' '^\sideways_u' 'Modifier letter small sideways u'
add-unicode 'ᵔ' '^\top_half_o' 'Modifier letter small top half o'
add-unicode '𐞬' '^\ts_digraph' ''
add-unicode '✦' 'blacklozenge' 'Black four pointed star'
add-unicode '🚧' 'construction' 'Construction sign'
add-unicode 'º' 'ordmasculine' 'Masculine ordinal indicator'
add-unicode '≓' 'risingdotseq' 'Image of or approximately equal to'
add-unicode '℗' 'textcircledP' 'Sound recording copyright'
add-unicode '⁒' 'textdiscount' 'Commercial minus sign'
add-unicode '▿' 'triangledown' 'White down-pointing small triangle'
add-unicode '◃' 'triangleleft' 'White left-pointing small triangle'
add-unicode '𐞅' '^\b_with_hook' ''
add-unicode 'ᶝ' '^\c_with_curl' 'Modifier letter small c with curl'
add-unicode '𐞌' '^\d_with_hook' ''
add-unicode '𐞋' '^\d_with_tail' ''
add-unicode '𐞓' '^\g_with_hook' ''
add-unicode 'ᵞ' '^\greek_gamma' 'Modifier letter small greek gamma'
add-unicode 'ʱ' '^\h_with_hook' 'Modifier letter small h with hook'
add-unicode '𐞛' '^\l_with_belt' ''
add-unicode 'ꟹ' '^\ligature_oe' 'Modifier letter small ligature oe'
add-unicode 'ᶬ' '^\m_with_hook' 'Modifier letter small m with hook'
add-unicode '𐞨' '^\r_with_tail' ''
add-unicode '𐞺' '^\s_with_curl' ''
add-unicode 'ᶳ' '^\s_with_hook' 'Modifier letter small s with hook'
add-unicode 'ᶹ' '^\v_with_hook' 'Modifier letter small v with hook'
add-unicode 'ᶽ' '^\z_with_curl' 'Modifier letter small z with curl'
add-unicode '⇐' 'Longleftarrow' 'Leftwards double arrow'
add-unicode '△' 'bigtriangleup' 'White up-pointing triangle'
add-unicode '▴' 'blacktriangle' 'Black up-pointing small triangle'
add-unicode '⋇' 'divideontimes' 'Division times'
add-unicode '≒' 'fallingdotseq' 'Approximately equal to or the image of'
add-unicode '↩' 'hookleftarrow' 'Leftwards arrow with hook'
add-unicode '↢' 'leftarrowtail' 'Leftwards arrow with tail'
add-unicode '↼' 'leftharpoonup' 'Leftwards harpoon with barb upwards'
add-unicode '⟵' 'longleftarrow' 'Long leftwards arrow'
add-unicode '↫' 'looparrowleft' 'Leftwards arrow with loop'
add-unicode '∡' 'measuredangle' 'Measured angle'
add-unicode '⋪' 'ntriangleleft' 'Not normal subgroup of'
add-unicode '∥' 'shortparallel' 'Parallel to'
add-unicode '∖' 'smallsetminus' 'Set minus'
add-unicode '⃝' 'textbigcircle' 'Combining enclosing circle'
add-unicode '℮' 'textestimated' 'Estimated symbol'
add-unicode '▹' 'triangleright' 'White right-pointing small triangle'
add-unicode '↿' 'upleftharpoon' 'Upwards harpoon with barb leftwards'
add-unicode '𐞤' '^\closed_omega' ''
add-unicode '𐞊' '^\dezh_digraph' ''
add-unicode '𐞐' '^\feng_digraph' ''
add-unicode '𐞮' '^\tesh_digraph' ''
add-unicode 'ᶛ' '^\turned_alpha' 'Modifier letter small turned alpha'
add-unicode '⇔' 'Leftrightarrow' 'Left right double arrow'
add-unicode '⇒' 'Longrightarrow' 'Rightwards double arrow'
add-unicode '↶' 'curvearrowleft' 'Anticlockwise top semicircle arrow'
add-unicode '⇊' 'downdownarrows' 'Downwards paired arrows'
add-unicode '↪' 'hookrightarrow' 'Rightwards arrow with hook'
add-unicode '⇇' 'leftleftarrows' 'Leftwards paired arrows'
add-unicode '↔' 'leftrightarrow' 'Left right arrow'
add-unicode '⋋' 'leftthreetimes' 'Left semidirect product'
add-unicode '⟶' 'longrightarrow' 'Long rightwards arrow'
add-unicode '↬' 'looparrowright' 'Rightwards arrow with loop'
add-unicode '×' 'multiplication' 'Multiplication sign'
add-unicode '∦' 'nshortparallel' 'Not parallel to'
add-unicode '⋫' 'ntriangleright' 'Does not contain as normal subgroup'
add-unicode '↣' 'rightarrowtail' 'Rightwards arrow with tail'
add-unicode '⇀' 'rightharpoonup' 'Rightwards harpoon with barb upwards'
add-unicode '∢' 'sphericalangle' 'Spherical angle'
add-unicode '◦' 'textopenbullet' 'White bullet'
add-unicode '⊴' 'trianglelefteq' 'Normal subgroup of or equal to'
add-unicode '↾' 'uprightharpoon' 'Upwards harpoon with barb rightwards'
add-unicode 'ꟸ' '^\H_With_Stroke' 'Modifier letter capital h with stroke'
add-unicode 'ᵕ' '^\bottom_half_o' 'Modifier letter small bottom half o'
add-unicode '𐞕' '^\h_with_stroke' ''
add-unicode 'ᶤ' '^\i_with_stroke' 'Modifier letter small i with stroke'
add-unicode '𐞢' '^\o_with_stroke' ''
add-unicode 'ᵌ' '^\turned_open_e' 'Modifier letter small turned open e'
add-unicode 'ʵ' '^\turned_r_hook' 'Modifier letter small turned r with hook'
add-unicode '▽' 'bigtriangledown' 'White down-pointing triangle'
add-unicode '↺' 'circlearrowleft' 'Anticlockwise open circle arrow'
add-unicode '↷' 'curvearrowright' 'Clockwise top semicircle arrow'
add-unicode '⇃' 'downleftharpoon' 'Downwards harpoon with barb leftwards'
add-unicode '↽' 'leftharpoondown' 'Leftwards harpoon with barb downwards'
add-unicode '⇆' 'leftrightarrows' 'Leftwards arrow over rightwards arrow'
add-unicode '⇎' 'nLeftrightarrow' 'Left right double arrow with stroke'
add-unicode '↮' 'nleftrightarrow' 'Left right arrow with stroke'
add-unicode '⋬' 'ntrianglelefteq' 'Not normal subgroup of or equal to'
add-unicode '⇄' 'rightleftarrows' 'Rightwards arrow over leftwards arrow'
add-unicode '⋌' 'rightthreetimes' 'Right semidirect product'
add-unicode '⇝' 'squigarrowright' 'Rightwards squiggle arrow'
add-unicode '‽' 'textinterrobang' 'Interrobang'
add-unicode '♪' 'textmusicalnote' 'Eighth note'
add-unicode '⊵' 'trianglerighteq' 'Contains as normal subgroup or equal to'
add-unicode '⊲' 'vartriangleleft' 'Normal subgroup of'
add-unicode '𐞗' '^\heng_with_hook' ''
add-unicode '↻' 'circlearrowright' 'Clockwise open circle arrow'
add-unicode '⇂' 'downrightharpoon' 'Downwards harpoon with barb rightwards'
add-unicode '⋭' 'ntrianglerighteq' 'Does not contain as normal subgroup or equal'
add-unicode '⇁' 'rightharpoondown' 'Rightwards harpoon with barb downwards'
add-unicode '⇉' 'rightrightarrows' 'Rightwards paired arrows'
add-unicode '↞' 'twoheadleftarrow' 'Leftwards two headed arrow'
add-unicode '⊳' 'vartriangleright' 'Contains as normal subgroup'
add-unicode '𐞩' '^\r_with_fishhook' ''
add-unicode 'ᶟ' '^\reversed_open_e' 'Modifier letter small reversed open e'
add-unicode '▾' 'blacktriangledown' 'Black down-pointing small triangle'
add-unicode '◂' 'blacktriangleleft' 'Black left-pointing small triangle'
add-unicode '⇋' 'leftrightharpoons' 'Leftwards harpoon over rightwards harpoon'
add-unicode '⇌' 'rightleftharpoons' 'Rightwards harpoon over leftwards harpoon'
add-unicode '₡' 'textcolonmonetary' 'Colon sign'
add-unicode '※' 'textreferencemark' 'Reference mark'
add-unicode '↠' 'twoheadrightarrow' 'Rightwards two headed arrow'
add-unicode 'ᶮ' '^\n_with_left_hook' 'Modifier letter small n with left hook'
add-unicode 'ꭟ' '^\u_with_left_hook' 'Modifier letter small u with left hook'
add-unicode '⇔' 'Longleftrightarrow' 'Left right double arrow'
add-unicode '▸' 'blacktriangleright' 'Black right-pointing small triangle'
add-unicode '⟷' 'longleftrightarrow' 'Long left right arrow'
add-unicode '‱' 'textpertenthousand' 'Per ten thousand sign'
add-unicode '𐞰' '^\v_with_right_hook' ''
add-unicode '↭' 'leftrightsquigarrow' 'Left right wave arrow'
add-unicode '⁄' 'textfractionsolidus' 'Fraction slash'
add-unicode 'ʶ' '^\capital_inverted_r' 'Modifier letter small capital inverted r'
add-unicode 'ʵ' '^\turned_r_with_hook' 'Modifier letter small turned r with hook'
add-unicode '𐞡' '^\turned_y_with_belt' ''
add-unicode '𐞔' '^\capital_g_with_hook' ''
add-unicode '𐞜' '^\capital_l_with_belt' ''
add-unicode 'ᶨ' '^\j_with_crossed-tail' 'Modifier letter small j with crossed-tail'
add-unicode 'ꭞ' '^\l_with_middle_tilde' 'Modifier letter small l with middle tilde'
add-unicode 'ᶪ' '^\l_with_palatal_hook' 'Modifier letter small l with palatal hook'
add-unicode 'ᶵ' '^\t_with_palatal_hook' 'Modifier letter small t with palatal hook'
add-unicode '𐞍' '^\d_with_hook_and_tail' ''
add-unicode '𐞉' '^\dz_digraph_with_curl' ''
add-unicode '𐞫' '^\tc_digraph_with_curl' ''
add-unicode 'ᶧ' '^\capital_i_with_stroke' 'Modifier letter small capital i with stroke'
add-unicode 'ᶡ' '^\dotless_j_with_stroke' 'Modifier letter small dotless j with stroke'
add-unicode 'ᶩ' '^\l_with_retroflex_hook' 'Modifier letter small l with retroflex hook'
add-unicode 'ᶯ' '^\n_with_retroflex_hook' 'Modifier letter small n with retroflex hook'
add-unicode 'ˤ' '^\reversed_glottal_stop' 'Modifier letter small reversed glottal stop'
add-unicode '𐞯' '^\t_with_retroflex_hook' ''
add-unicode 'ᶼ' '^\z_with_retroflex_hook' 'Modifier letter small z with retroflex hook'
add-unicode '𐞏' '^\closed_reversed_open_e' ''
add-unicode 'ꭝ' '^\l_with_inverted_lazy_s' 'Modifier letter small l with inverted lazy s'
add-unicode 'ᶭ' '^\turned_m_with_long_leg' 'Modifier letter small turned m with long leg'
add-unicode '𐞦' '^\turned_r_with_long_leg' ''
add-unicode '𐞟' '^\lezh_with_retroflex_hook' ''
add-unicode '𐞘' '^\dotless_j_with_stroke_and_hook' ''
add-unicode '𐞈' '^\dz_digraph_with_retroflex_hook' ''
add-unicode '𐞝' '^\l_with_retroflex_hook_and_belt' ''
add-unicode '𐞭' '^\ts_digraph_with_retroflex_hook' ''
add-unicode '𐞧' '^\turned_r_with_long_leg_and_retroflex_hook' ''

፠
